### ISSUE TITLE
How do I tell google_fonts lib is using assets font instead of requesting it?

### ISSUE THREAD

**Issue by shane99a** [material-foundation/google-fonts-flutter#103]
I think during debug mode it should log the http request to get the font file, so that its clear if it is using the cache/assets file or not.

Also slightly related question, if I am loading the fonts from assets, should I expect to have the font loaded before the app loads? I shouldn't be seeing a placeholder font beforehand right? Need to know if I can use this for inital splash/loading screen.

**Comment by clocksmith** [comment]
To answer the title's question, you can use `GoogleFonts.config.allowRuntimeFetching = false` and see if the font is still displayed.

When fonts are coming from assets, they still need to be loaded by the FontLoader, which is very fast when loading from assets, but not necessarily done before the first screen. We might need to make a preload function available to support this case.

**Comment by shane99a** [comment]
Hey, I have confirmed that it doesn't show up in time for initial loading screen. I'll just use icons instead.

**Comment by MrMuMu** [comment]
I can also confirm that fonts do not load in time on landing/initial page. It would be good to have an api to force loading the font before rendering.

**Comment by nxcco** [comment]
@MrMuMu Yes I'm experiencing the exact same issue. I solved it by loading empty Text widgets with the necessary text fonts in my loading screen. Hope a functionality like you've already mentioned will be added soon!

**Comment by MrMuMu** [comment]
@nxcco I have downloaded fonts from [here](https://fonts.google.com) and loaded them as local font assets as a workaround.
