### ISSUE TITLE
[BUG]  font families missing

### ISSUE THREAD

**Issue by ccheever** [material-foundation/google-fonts-flutter#108]
**Describe the bug**

There are 991 font families listed at fonts.google.com but there are only 964 families listed in the fontDirectory that is downloaded to generate this package. So, ~ 27 fonts are missing.

One example of this is [Balsamiq Sans](https://fonts.google.com/specimen/Balsamiq+Sans).

#105 is another example of this.

**To Reproduce**
1. Download the directory pb file as in the generator and decode it so it can be inspected.
2. See that there are 964 font families in that file.
3. See that some fonts, like Balsamiq Sans, are not available in google_fonts Flutter.
4. See that Balsamiq Sans is available on fonts.google.com.

I can't really figure out a pattern for which fonts are missing, though it seems like some of them might have been added recently?

Also, some fonts like Baloo are present in this package but aren't present on fonts.google.com and seem to have been replaced by Baloo 2.

**Comment by ccheever** [comment]
I think the way to fix this is to use the API documented on fonts.google.com rather than using the protobufs directory that is in the generator code which seems to only work for an older iteration of google fonts.

**Comment by dfdgsdfg** [comment]
Also, I can not use `ThemeData`'s default font family.

```dart
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final appName = 'Custom Themes';

    return MaterialApp(
      title: appName,
      theme: ThemeData(
        // Define the default font family. How?
        fontFamily: '???',
      ),
      home: MyHomePage(
        title: appName,
      ),
    );
  }
}
```

**Comment by wolframm** [comment]
It appears Balsamiq Sans is still missing in release 1.1.0. Please make a complete release.

**Comment by ccheever** [comment]
https://github.com/expo/google-fonts/tree/master/font-packages/balsamiq-sans#readme
 ?

**Comment by JaffaKetchup** [comment]
Hello,
I have found that the font Jost is also missing.
Any news on this?
Thanks.

**Comment by johnsonmh** [comment]
Hi, I believe all the fonts mentioned in this bug are now available.

`Baloo`, `Jost`, and `Balsamiq Sans`.
