### ISSUE TITLE
Fonts URIs are using http: rather than https?  Mixed Content errors

### ISSUE THREAD

**Issue by sgehrman** [material-foundation/google-fonts-flutter#11]
I deployed to firebase and got this:

Mixed Content: The page at 'https://therapist-training.firebaseapp.com/#/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmWUlvAx05IsDqlA.ttf'. This request has been blocked; the content must be served over HTTPS

**Comment by johnsonmh** [comment]
https://github.com/material-foundation/google-fonts-flutter/pull/55 has landed and I just published [version 0.3.3](https://pub.dev/packages/google_fonts/versions/0.3.3) to pub. This should be fixed now! 

Thank you for the PR @jld3103!
