### ISSUE TITLE
Doesn't work with brightness

### ISSUE THREAD

**Issue by codegrue** [material-foundation/google-fonts-flutter#110]
In the below sample, the theme text doesn't change to white as the brightness should set it. Other text not affected by GoogleFonts toggles white or black as desired.

```
MaterialApp(
  theme: ThemeData(
    primarySwatch: Colors.teal,
    brightness: Brightness.dark, // or Brightness.light
    textTheme: GoogleFonts.latoTextTheme(
      Theme.of(context).textTheme,
    ),
  ),
);
```

**Comment by codegrue** [comment]
This works but seems repetative:

``` dart
ThemeData(
        primarySwatch: Colors.teal,
        brightness: Brightness.dark,
        textTheme: GoogleFonts.comfortaaTextTheme(
          ThemeData(
            primarySwatch: Colors.teal,
            brightness: Brightness.dark,
          ).textTheme,
        ),
      ),
```

**Comment by codegrue** [comment]
Solution I came up with. Please close if this is the best way to do this:

``` dart
MaterialApp(
  theme: _buildTheme(Brightness.dark),
);

  ThemeData _buildTheme(brightness) {
    var baseTheme = ThemeData(
        primarySwatch: Colors.teal,
        brightness: brightness,
        visualDensity: VisualDensity.adaptivePlatformDensity);

    return baseTheme.copyWith(
      textTheme: GoogleFonts.comfortaaTextTheme(
        baseTheme.textTheme,
      ),
    );
  }
```

**Comment by cinehaus** [comment]
I had same problem - text not reacting to brightness change after applying Google fonts as global text theme. 

I like your solution, but perhaps this one is slightly easier: Text seems to adapt as expected (from dark on light background to light on dark background) when in Material App Widget, you not only specify theme:, but also specify darktheme:, for example like shown below.

This also allows you to toggle Appearance in you simulator without touching the actual code.

    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Flutter Demo',
      theme: ThemeData(
        brightness: Brightness.light,
        primarySwatch: Colors.blue,
        textTheme: GoogleFonts.openSansTextTheme(
          Theme.of(context).textTheme,
        ),
      ),
      darkTheme: ThemeData(
        brightness: Brightness.dark,
        accentColor: Colors.blueAccent,
      ),
      home: MyHomePage(
        title: 'Demo App',
      ),
    );
