### ISSUE TITLE
version solving failed

### ISSUE THREAD

**Issue by TN888** [material-foundation/google-fonts-flutter#111]
I've tried to add `google_fonts` to the project's `pubspec.yaml`, but when I hit `pub get`, I get the following message:

```
Because <project_name> depends on google_fonts >=1.1.0 which requires Flutter SDK version ^1.17.0, version solving failed.
pub get failed (1; Because <project_name> depends on google_fonts >=1.1.0 which requires Flutter SDK version ^1.17.0, version solving failed.)
```
Here's my Flutter version:
```
Flutter 1.17.0-3.3.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 0da1ab0922 (3 weeks ago) • 2020-04-28 11:02:34 -0700
Engine • revision 376ad6a64b
Tools • Dart 2.8.0
```
How to solve it?

**Comment by madscs11** [comment]
You are on some beta channel so it might be because of that.
I had the same problem but fixed it by switching to the stable flutter channel.

`flutter channel stable`

And then I upgraded to the most recent version of flutter:

`flutter upgrade`

**Comment by johnsonmh** [comment]
Looks like this issue was resolved with a `flutter upgrade`, feel free to reopen if it's still ocurring.
