### ISSUE TITLE
CJK fonts

### ISSUE THREAD

**Issue by X-Wei** [material-foundation/google-fonts-flutter#115]
In previous versions like `0.2.0`, I can use `GoogleFonts.notoSansSCTextTheme()` to get the CJK-variant of the NotoSans font. 

But with latest version there's only `notoSansTextTheme()`, with that, the CJK characters cannot be properly displayed.

So how to properly set the CJK font with latest package?

**Comment by guidezpl** [comment]
Hi @X-Wei, certain Noto fonts are currently missing and will be added in a future version. Please follow #126 for updates
