### ISSUE TITLE
GoogleFonts *volkhov* Font Text word last letter not displaying 

### ISSUE THREAD

**Issue by AnkushCodes** [material-foundation/google-fonts-flutter#117]
**Describe the bug**
In Flutter Web 
GoogleFonts *volkhov* Font Text word last letter not displaying 
Condition:
 1)when space added in word it work perfectly but not whole word without space
2) In mobile platform working bug introduce in Flutter Web

package with version: google_fonts: ^1.1.0

**Comment by guidezpl** [comment]
Closing this since it is quite an old issue. Please reopen/open a new issue if you're still facing this issue with `2.2.0` and include:
* a small code sample
* the output of`flutter doctor -v`
