### ISSUE TITLE
Proper folder naming / structure

### ISSUE THREAD

**Issue by subzero911** [material-foundation/google-fonts-flutter#118]
It is not clear from the docs.
Should I necessary name the folder `google_fonts` and make it a top-level folder?
I put my font into `assets/fonts/montserrat/`, and wrote this path in my pubspec, and it seems to be working too.
Also, it is not convenient to keep all my fonts in the same folder without subfolders. Each has it's own OFL.txt, and they will overwrite each other.

**Comment by guidezpl** [comment]
Hi, it's not. as long as it's specified somehow in the assets it will be picked up
