### ISSUE TITLE
Package started failing on Web

### ISSUE THREAD

**Issue by esentis** [material-foundation/google-fonts-flutter#122]
The package suddenly started failing on Flutter Web giving tons of errors, errors which were not very clear that came from the package. I had to break down the whole app to components, to narrow it down to google fonts. Just by importing it, the app crashes. The project compiles without any errors on mobile.
Below I'll show some screenshots of the errors, hope it helps. Keep in mind the package was working flawlessly till yesterday. I haven't introduced any changes from my part from what I can tell. 

![image](https://user-images.githubusercontent.com/52862600/93689339-73be0600-fad6-11ea-9f90-eeec54ace7e4.png)

**Because of the error log being very long i'll show 3-4 lines from each file giving the error.**
![image](https://user-images.githubusercontent.com/52862600/93689432-25f5cd80-fad7-11ea-92b8-3da4b8735aca.png)

![image](https://user-images.githubusercontent.com/52862600/93689436-2e4e0880-fad7-11ea-8aeb-dff5c37b6663.png)

![image](https://user-images.githubusercontent.com/52862600/93689441-36a64380-fad7-11ea-9b6a-f78bdc1807ca.png)

![image](https://user-images.githubusercontent.com/52862600/93689446-3f971500-fad7-11ea-8184-c0d60f925087.png)

![image](https://user-images.githubusercontent.com/52862600/93689455-5473a880-fad7-11ea-8d16-0c7e6cf9a922.png)

![image](https://user-images.githubusercontent.com/52862600/93689459-5f2e3d80-fad7-11ea-8adb-4b10f38682f6.png)

My yaml file:
![image](https://user-images.githubusercontent.com/52862600/93689490-ac121400-fad7-11ea-9d60-3b890eae3204.png)

**Comment by PaulHalliday** [comment]
I'm also experiencing the same issue as above.

**Comment by PaulHalliday** [comment]
Fixed this by setting `path_provider` to `1.6.14` instead of `1.6.16`:

```
  path_provider:
    dependency: transitive
    description:
      name: path_provider
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.6.14"
```

**Comment by esentis** [comment]
> Fixed this by setting `path_provider` to `1.6.14` instead of `1.6.16`:
> 
> ```
>   path_provider:
>     dependency: transitive
>     description:
>       name: path_provider
>       url: "https://pub.dartlang.org"
>     source: hosted
>     version: "1.6.14"
> ```

Awesome, downgrading path_provider to version 1.6.14 fixed the issue.
![image](https://user-images.githubusercontent.com/52862600/93782142-e3490800-fc32-11ea-9528-b9eba42d6981.png)

Final YAML file:
![image](https://user-images.githubusercontent.com/52862600/93782327-1e4b3b80-fc33-11ea-93cf-bc883b2a839e.png)

**Comment by cadaats** [comment]
So is this caused by flutter upgrade or the fonts upgrade ?

**Comment by guidezpl** [comment]
Closing this since it's an old issue and `path_provider` has had a major bump (`2.0.8`). If this issue crops up again, please file a new issue
