### ISSUE TITLE
[BUG] Some fonts should be made unavailable

### ISSUE THREAD

**Issue by kubaprzetakiewicz** [material-foundation/google-fonts-flutter#127]
`Muli` was renamed to `Mulish` but is still present in the `google_fonts.dart`.

One thing we could do is check `https://fonts.google.com/specimen/x` URLs and remove unavailable fonts.

**Comment by guidezpl** [comment]
Mulish is now available but you're right that Muli is still present. I'll repurpose this issue to remove unavailable fonts
