### ISSUE TITLE
[NNBD] Migrate entire library to NNBD

### ISSUE THREAD

**Issue by pennzht** [material-foundation/google-fonts-flutter#135]
When upstream packages are ready, migrate the remaining files of this package to NNBD.
This includes all `.dart` files with a `// @dart=2.9` annotation.

* Once `path_provider` is migrated, the main library can be completely migrated to NNBD.

**Comment by stuartmorgan** [comment]
The core dependencies (not sure about all the dev dependencies, but those are not necessarily blockers) are now migrated.

**Comment by mzdm** [comment]
Was anyone successful in generating null-safe _generator/fonts.pb.dart_ file? I can't get the **protoc-gen-dart** plugin working to generate it.
