### ISSUE TITLE
[BUG] Roboto Font used before Google Font is applied

### ISSUE THREAD

**Issue by nxcco** [material-foundation/google-fonts-flutter#143]
When you want to display a text with a specific font (on mobile; during development but also in production), there is a little lag between. During this lag, the default Roboto font is being shown. That is also the case when the used fonts are already cached and even pre-bundled.

**Comment by Akshar-Patel** [comment]
This happens for me as well.

**Comment by rocboronat** [comment]
Same here. I thought the bundled font would appear with no lag. It should be clarified on the readme file, because there's no way this library, as is right now, could make an app look like a real native app 😢

**Comment by nxcco** [comment]
For everyone encountering this issue: Use the usual way to bind font files in Flutter. At least that's what solved it for me.
