### ISSUE TITLE
[BUG] Unhandled Exception: type 'Future<ByteData?>' is not a subtype of type 'Future<ByteData>' 

### ISSUE THREAD

**Issue by aliak00** [material-foundation/google-fonts-flutter#146]
**Describe the bug**
Whenever I start a new app I hit some break point in VSCode and an unhandled exception gets printed to the console:

```
[VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: type 'Future<ByteData?>' is not a subtype of type 'Future<ByteData>' in type cast
#0      _loadFontByteData package:google_fonts/src/google_fonts_base.dart:187
<asynchronous suspension>
```

**To Reproduce**
1. `flutter create blah
2. Add a `Text` widget in a `Column` in a `Center`
3. Use this:
  ```
     Text(
          "blah blah",
          style: GoogleFonts.lato(
            textStyle: TextStyle(
              color: Colors.cyan[900],
              fontSize: 16,
              wordSpacing: 3,
              letterSpacing: 7,
              fontWeight: FontWeight.bold,
            ),
          ),
        ),
  ``` 

**Expected behavior**
App doesn't throw an exception

**Include the contents of your `google_fonts` directory**
No google_fonts directory

**Screenshots**
![image](https://user-images.githubusercontent.com/2638284/107926032-7d5c7480-6f75-11eb-9442-3aa10596eac8.png)

**Emulator:**
 - OS: iOS
 - Version: 14.4
 - Model: 12 Pro Max

google_fonts version: "2.0.0-nullsafety.0"

**Comment by El-Danoun** [comment]
I have the same issue, without Column or Center widget. Just with a Align widget :

	Align(alignment: Alignment.bottomCenter,
		child: Padding(
			padding: const EdgeInsets.only(
				bottom: 20, 
				left: 20,
				right: 20),
				child: Text('blah blah',
					textAlign: TextAlign.left,
					style: GoogleFonts.roboto(
						textStyle: const TextStyle(fontSize: 15),
					color: Colors.white))))`

**Comment by sma** [comment]
The problem is that `byteData` which is passed to `loadFontByteData` is a `ByteData?` future, but when passed to `fontLoader.addFont` it is wrongly cast to a `ByteData` future. I think, the test `await byteData != null` is supposed to make sure, that the future's value is never null, and therefore the cast is possible, but this isn't how casts work. Furthermore, the result is thrown away.

This is a simple workaround (see https://github.com/material-foundation/google-fonts-flutter/blob/develop/lib/src/google_fonts_base.dart#L187) to correctly "cast" the type:

```dart
    fontLoader.addFont(byteData.then((data) => data!));
```

However, it seems wasteful to first await the future and then not to use the value, so this might be a better approach:

```dart
  if (byteData != null) {
    final fontData = await byteData;
    if (fontData != null) {
      final fontLoader = FontLoader(familyWithVariantString);
      fontLoader.addFont(Future.value(fontData));
      await fontLoader.load();
    }
  }
```

**Comment by gaetschwartz** [comment]
Any news ? This is pretty blocking so it would be great if it could be fixed. The mixed isn't even hard.

**Comment by pennzht** [comment]
I cannot replicate this issue. Could you please post your entire `lib/main.dart` here?

**Comment by sma** [comment]
The static type error in line 187 should be obvious just by looking at the linked source code I, but here you are:

```dart
void main() {
  runApp(ProviderScope(child: MyApp()));
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
        primarySwatch: Colors.amber,
        textTheme: GoogleFonts.lailaTextTheme(),
      ),
      home: Scaffold(),
    );
  }
}
```

This emits
```
[VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: type 'Future<ByteData?>' is not a subtype of type 'Future<ByteData>' in type cast
```
upon running the above code on iOS.

**Comment by clocksmith** [comment]
I could not repro on iphone 12 pro max on macos 11.2.1. Could you share your pubspec? Or just the environment sdk version?

**Comment by sma** [comment]
Sure.
```
[✓] Flutter (Channel master, 1.27.0-5.0.pre.115, on macOS 11.2.1 20D74 darwin-x64, locale de-DE)
    • Flutter version 1.27.0-5.0.pre.115 at /Users/sma/Work/flutter
    • Framework revision b5139515c1 (26 hours ago), 2021-02-23 11:25:01 -0800
    • Engine revision 07afcf7d0f
    • Dart version 2.13.0 (build 2.13.0-52.0.dev)

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1
```

```
environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^0.13.0-nullsafety.3
  google_fonts: ^2.0.0-nullsafety.0
```

**Comment by clocksmith** [comment]
Ok I was able to reproduce.

With:
```
environment:
  sdk: ">=2.1.0 <3.0.0"
```
there is no issue,  but if that is changed to:
```
environment:
  sdk: ">=2.12.0-0 <3.0.0"
```
then the error is produced:
```
[VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: type 'Future<ByteData?>' is not a subtype of type 'Future<ByteData>' in type cast
#0      _loadFontByteData (package:google_fonts/src/google_fonts_base.dart:187:33)
<asynchronous suspension>
```

@kevmoo any idea why that might be?

**Comment by kevmoo** [comment]
Yup. The static type is different.

So this is why we'd have to wrap the value with `Future.value(...)` in the PR

**Comment by gaetschwartz** [comment]
@kevmoo Is there anything wrong with my PR ?

**Comment by sma** [comment]
PR 149 does not fix the static type error, as it still tries to cast a `Future<ByteData?>` to a `Future<ByteData>` in line 189. See above for two alternative fixes I proposed.

**Comment by gaetschwartz** [comment]
@sma it does.

**Comment by sma** [comment]
Since about 8 minutes :-)

**Comment by gaetschwartz** [comment]
My bad, worked on the example so I assumed it would work. Didn't make the tests fail either. Weird. Fixed it :)
