### ISSUE TITLE
google_fonts: Failed to load font when Chrome debug session in VS Code is started

### ISSUE THREAD

**Issue by bambinoua** [material-foundation/google-fonts-flutter#147]
I am using your package on PC which usually does not have Internet connection. When I started VS Code in debug session using Cheome I get this error message:
> Failed to load font Roboto at https://fonts.gstatic.com/s/roboto/V20/....ttf
> Error: google_fonts was unable to load font Roboto-Regular

I tried to implements local storage using `assets`. I downloaded *all* Roboto-fonts into google_fonts directory (as described) but when I started Chrome debug session I got the same error. Please, help to fix this.

**Comment by guidezpl** [comment]
Closing in favour of #70
