### ISSUE TITLE
Web search results were displayed at the wrong position

### ISSUE THREAD

**Issue by Wissperwind** [material-foundation/google-fonts-flutter#153]
I use selectable Text. I can select it and I can right click ist.

It seems to me that the underlying code is as follows:
```
if (Math.random() < 0.1) {
    showSelectableTextContextMenu();
} else {
    showNormalBrowserContextMenu();
}
```

So most of the time I get the normal context Menu. And in some rare cases I get the correct context menu where I can copy things.

Correct contextMenu:
![Screenshot (5)](https://user-images.githubusercontent.com/20759873/112170707-90f19f80-8bf3-11eb-8e9d-69593146f6f6.png)

Wrong context menu:
![Screenshot (6)](https://user-images.githubusercontent.com/20759873/112170735-964eea00-8bf3-11eb-8c8f-7d07d2e4ecd6.png)

Code sample:

```
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: "Test",
      home: TestPage(),
    );
  }
}

class TestPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text("Test")),
      body: Container(
        child: Center(
          child: ElevatedButton(
            onPressed: () {
              testAlert(context);
            },
            child: Text("PressMe"),
          ),
        ),
      ),
    );
  }

  void testAlert(BuildContext context) {
    var alert = AlertDialog(
      title: Text("Test"),
      content: SelectableText(
          "Done.. lalala you can search me if you want! \n some other line,\n and some more lines\n bla\n bla\n bla\n bla\n bla\n bla\n bla\n and some more messages",
          style: GoogleFonts.sourceCodePro()),
    );

    showDialog(
        context: context,
        builder: (BuildContext context) {
          return alert;
        });
  }
}
```

**Comment by Wissperwind** [comment]
This seems to be a problem of the dynamic loading of the fint files from the google servers.
I think the text structure, where the words are in the screen is defined with the standard font. After that the fint files were loaded and the new font is applied without changing the definiton of where the words are on the screen. This leads to wrong context menus and wrong search result markers. The problem is gone if you provide the ttf files in the assets.

**Comment by guidezpl** [comment]
I'm no longer able to repro this issue, and will thus be closing it. If it still occurs, please file a new issue with all requested information. Thanks!
