### ISSUE TITLE
[Request] Update Google Fonts

### ISSUE THREAD

**Issue by mzdm** [material-foundation/google-fonts-flutter#158]
Material icons are being updated right now:
https://github.com/flutter/flutter/pull/76607
https://github.com/flutter/flutter/pull/78311

This is a request to update Google Fonts as well.

This would resolve these missing font issues #156 #127 #128 #120 #108.

Tagging @willlarche who [has done this request before (Material Icons)](https://github.com/flutter/flutter/issues/71233#issuecomment-736238912) 🙏

**Comment by guidezpl** [comment]
Thanks for filing and looking for relevant issues! cc @johnsonmh @clocksmith

**Comment by marchellodev** [comment]
+1

**Comment by IvanFLeon** [comment]
+1

**Comment by bernaferrari** [comment]
They updated now.

**Comment by mzdm** [comment]
Thanks for updating it @johnsonmh.
The referenced issues can be closed as well.

I've noticed that some language-specific fonts were not added in that update (e.g. Noto Serif JP)
https://fonts.google.com/?query=noto+sans
https://fonts.google.com/?query=noto+serif
