### ISSUE TITLE
[REQUEST] Add Google Noto Fonts

### ISSUE THREAD

**Issue by marchellodev** [material-foundation/google-fonts-flutter#159]
Hey, is it possible to add [Google Noto fonts ](https://www.google.com/get/noto) to this library as well?

Some of them, for example [Noto Sans Sinhala](https://www.google.com/get/noto/#sans-sinh), are not available on Google Fonts

**Comment by marchellodev** [comment]
Related to https://github.com/google/fonts/issues/3233

**Comment by mzdm** [comment]
They can't add a font that is not part of fonts.google.com. So this issue really is not related to this repository

**Comment by innoxxicide** [comment]
> They can't add a font that is not part of fonts.google.com. So this issue really is not related to this repository

But "Noto Sans SC", "Noto Sans JP" and "Noto Sans KR" families are part of fonts.google.com, and we still can't access it with Flutter package. So, we're kindly asking for update with Noto fonts support.

**Comment by mzdm** [comment]
> > They can't add a font that is not part of fonts.google.com. So this issue really is not related to this repository
> 
> But "Noto Sans SC", "Noto Sans JP" and "Noto Sans KR" families are part of fonts.google.com, and we still can't access it with Flutter package. So, we're kindly asking for update with Noto fonts support.

I was talking about [Noto Sans Sinhala](https://fonts.google.com/?query=sinhala) - this is not available on Google Fonts. It depends on https://github.com/google/fonts/issues/3233 which seems like they will be added soon.

As for other Noto Sans fonts there are already posted issues about them, https://github.com/material-foundation/google-fonts-flutter/issues/126 https://github.com/material-foundation/google-fonts-flutter/issues/105
