### ISSUE TITLE
[BUG] dependency error with flutter_drive and crypto

### ISSUE THREAD

**Issue by acanteror** [material-foundation/google-fonts-flutter#161]
**Describe the bug**
I get an dependency error with google_fonts 2.0.0 and flutter_drive

When I try to get dependencies with google_fonts ^2.0.0 and flutter_drive I get the next unmatch dependency error

Because every version of flutter_driver from sdk depends on crypto 2.1.5 and google_fonts >=2.0.0-nullsafety.0 depends on crypto ^3.0.0, flutter_driver from sdk is incompatible with google_fonts >=2.0.0-nullsafety.0.
So, because rae_test depends on both google_fonts ^2.0.0 and flutter_driver any from sdk, version solving failed.
pub get failed (1; So, because rae_test depends on both google_fonts ^2.0.0 and flutter_driver any from sdk, version solving failed.)

**Comment by aruntomar** [comment]
I"m also getting the same error.

**Comment by locskot** [comment]
So am I.

**Comment by guidezpl** [comment]
Since `flutter_driver` from the current stable release uses `3.0.1`, this issue can be closed
