### ISSUE TITLE
[feature] Chinese font support

### ISSUE THREAD

**Issue by jinfagang** [material-foundation/google-fonts-flutter#162]
Hi, this lib is very convinient for developers to change font, but I saw there is not doc or relate description on how to using Chinese font.

Does it support for now? If so, how to use them?

**Comment by guidezpl** [comment]
Hi, the package now supports a number of Chinese fonts (e.g. ZCOOL, Ma Shan Zheng
, etc.) but not yet Noto. For that, please follow #126
