### ISSUE TITLE
[BUG] Font weight different than from fonts.google.com

### ISSUE THREAD

**Issue by devj3ns** [material-foundation/google-fonts-flutter#163]
**Describe the bug**
When downloading fonts manually from [fonts.google.com](fonts.google.com) they are thinner than the ones which are used by the package (see screenshots).

**Example App**
https://github.com/devj3ns/google_fonts_test

**To Reproduce**
Steps to reproduce the behaviour:
1. Run the example app.
2. You will see the fonts which are downloaded from the package in the background.
3. Uncomment the path to the downloaded fonts in pubspec.yaml.
4. Restart the app.
5. Now you will see the fonts which are downloaded manually from [fonts.google.com](fonts.google.com). They are thinner.

**Expected behaviour**
The fonts which are used by the package should be the same as the ones on fonts.google.com.

**Screenshots**
From the package:
![from_package](https://user-images.githubusercontent.com/20878653/116918634-724de200-ac50-11eb-8e95-194570aa76f4.png)

From [fonts.google.com](fonts.google.com):
![from_website](https://user-images.githubusercontent.com/20878653/116918653-7a0d8680-ac50-11eb-8894-103a7ab7a816.png)

Tested with Montserrat on the web with the latest Flutter version (2.0.6.) and google_fonts version (2.0.0).

**Comment by devj3ns** [comment]
Hey @timsneath. I tagged you because you are the last person who committed to this package :D 

Do you know who maintains this package? There are so many open issues to which nobody has ever replied or closed because they are outdated.

**Comment by sooxt98** [comment]
This is old issue, take a look at the work around there
https://github.com/material-foundation/google-fonts-flutter/issues/35

**Comment by guidezpl** [comment]
Closing in favour of #35

**Comment by biniyam-a2sv** [comment]
The font-weight should also have bolder versions than 900
