### ISSUE TITLE
[BUG] Undescriptive error message: "Error loading AssetManifest.json, e: Null check operator used on a null value"

### ISSUE THREAD

**Issue by cstmth** [material-foundation/google-fonts-flutter#172]
**Describe the bug**
I am getting the exception ```Error loading AssetManifest.json, e: Null check operator used on a null value``` on start of my app. It occurs the before the first widget is rendered (which has Google Fonts text).

You can find extensive logs here, because I thought this was a Flutter issue: <https://github.com/flutter/flutter/issues/85457>

The exception is not actually an exception but only a print statement concated with an error. The stack trace had to be extracted by setting a breakpoint first and then getting it via dev tools. This is the stack trace:

```
#0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:222:39)
#1      AssetBundle.loadString (package:flutter/src/services/asset_bundle.dart:68:33)
#2      CachingAssetBundle.loadString.<anonymous closure> (package:flutter/src/services/asset_bundle.dart:165:56)
#3      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:311:23)
#4      CachingAssetBundle.loadString (package:flutter/src/services/asset_bundle.dart:165:27)
#5      AssetManifest._loadAssetManifestJson (package:google_fonts/src/asset_manifest.dart:31:28)
#6      AssetManifest.json (package:google_fonts/src/asset_manifest.dart:24:21)
#7      loadFontIfNecessary (package:google_fonts/src/google_fonts_base.dart:137:51)
#8      googleFontsTextStyle (package:google_fonts/src/google_fonts_base.dart:103:3)
#9      GoogleFonts.poppins (package:google_fonts/google_fonts.dart:75983:12)
#10     new DerHombergerSchwarzesBrettApp (package:der_homberger_schwarzes_brett/main.dart:23:30)
#11     main (package:der_homberger_schwarzes_brett/main.dart:6:10)
#12     _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:142:25)
#13     _rootRun (dart:async/zone.dart:1354:13)
#14     _CustomZone.run (dart:async/zone.dart:1258:19)
#15     _runZoned (dart:async/zone.dart:1789:10)
#16     runZonedGuarded (dart:async/zone.dart:1777:12)
#17     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:138:5)
#18     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
#19     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

**To Reproduce**
I actually have no clue what I have done wrong.

**Expected behavior**
No exception in the console

**Include the contents of your `google_fonts` directory**
I am sorry, I don't know where to find it. :(

**Smartphone (please complete the following information if applicable):**
 - Device: Pixel 2
 - OS: Android 12 (Emulator)

**Additional context**
The exception is "thrown" on line 34 in file ```asset_manifest.dart```. I have no clue what the file does, nor, obviously, how to resolve it.

**Comment by apco-afawcett** [comment]
I was having this same issue on a new project. Fixed by adding this line in main():

 WidgetsFlutterBinding.ensureInitialized();

**Comment by sadaakisz** [comment]
> I was having this same issue on a new project. Fixed by adding this line in main():
> 
> WidgetsFlutterBinding.ensureInitialized();

Worked like a charm!

**Comment by guidezpl** [comment]
We should provide a more helpful message

**Comment by ayushin** [comment]
If you put `WidgetsFlutterBinding.ensureInitialized();` outside of runZonedGuarded you will loose all your async exceptions. Bad solution.

**Comment by ayushin** [comment]
So basically the error is still there, just moving WidgetsFlutterBinding.ensureInitialized() outside of runZonedGuarded masks the error (and all other uncaught errors in async)
