### ISSUE TITLE
[BUG] Noto Serif SC is not in the plugin

### ISSUE THREAD

**Issue by marchellodev** [material-foundation/google-fonts-flutter#173]
https://fonts.google.com/specimen/Noto+Serif+SC?query=Noto+Serif+SC

**Comment by Gianthard-cyh** [comment]
It looks like some Noto Fonts on fonts.google.com is not supported, including Noto Serif SC ,Noto Serif JP ,Noto Serif KR and other Fonts except Noto Serif itself. However for other languages they are also needed. @guidezpl

**Comment by guidezpl** [comment]
Closing in favor of #126
