### ISSUE TITLE
[Feature request] GitHub Actions to automatically update the plugin

### ISSUE THREAD

**Issue by marchellodev** [material-foundation/google-fonts-flutter#174]
Hey, can you guys please set up GitHub action that will keep track of all the fonts available at https://fonts.google.com and automatically update the plugin as new fonts are added?

It seems like the majority of issues here are opened due to the missing fonts

**Comment by ManuLpz4** [comment]
You just need to run ```flutter pub upgrade```on your workflow :/
Why do you need an action for that?

**Comment by marchellodev** [comment]
Well, unfortunately, running `flutter pub upgrade` will not sync this plugin with fonts.google.com, pulling up the recently added fonts :)

**Comment by ManuLpz4** [comment]
Oh sorry, my bad, I misunderstood your comment ✋🏻

**Comment by guidezpl** [comment]
Fixed by https://github.com/material-foundation/google-fonts-flutter/pull/184, just waiting for an internal update to update the font manifest
