### ISSUE TITLE
[REQUEST] Add Shippori Mincho Fonts

### ISSUE THREAD

**Issue by takinok** [material-foundation/google-fonts-flutter#176]
**Describe the request**
I would like to Shippori Mincho to this package.
https://fonts.google.com/specimen/Shippori+Mincho?query=mincho

I actually tried to execute the following command. But NO change happened on the google_fonts.dart...
> dart generator/generator.dart

**Screenshots**
the result of generator command.
![スクリーンショット 2021-07-22 10 55 39](https://user-images.githubusercontent.com/49100289/126580639-a51818ed-521c-47e4-a440-f3333a977a8f.png)

**Comment by takinok** [comment]
I was noticed that the Shippori Mincho isn't included in the latest font directory(http://fonts.gstatic.com/s/f/directory3.pb) by debugging of the generator.dart.  I think this is the reason for other similar issues ( #105 , #108 , etc)

@johnsonmh , @clocksmith 
Could you give me any advice or comment about what should I do to solve this issue?

I'm appreciating this great library and the contribution of many people.

**Comment by cihadturhan** [comment]
Same here
I tried following fonts (which exist in google fonts)
- Bodoni Moda
- Train One
- Jost
and they don't exist [directory0003.pb](http://fonts.gstatic.com/s/f/directory003.pb)

Maybe there are another up-to-date directory?

**Comment by takinok** [comment]
> I think one way is to use google fonts api which is cumbersome but it returns all the fonts available on google fonts website
> 
> https://developers.google.com/fonts/docs/developer_api

Thank you for your comment, @cihadturhan !  And I'm sorry for my late response.
"direcotry0003.pb" is shown by "_getProtoUrl()" of "generator.dart" as the latest directory . So, I believe that is the latest one.

And as you said, usage of API is the alternative way. But I would like to fix/enhance this great package somehow.

```javascript
# generator.dart

/// Gets the latest font directory.
///
/// Versioned directories are hosted on the Google Fonts server. We try to fetch
/// each directory one by one until we hit the last one. We know we reached the
/// end if requesting the next version results in a 404 response.
/// Other types of failure should not occur. For example, if the internet
/// connection gets lost while downloading the directories, we just crash. But
/// that's okay for now, because the generator is only executed in trusted
/// environments by individual developers.
Future<Uri> _getProtoUrl({int initialVersion = 1}) async {
  var directoryVersion = initialVersion;

  Uri url(int directoryVersion) {
    final paddedVersion = directoryVersion.toString().padLeft(3, '0');
    return Uri.parse('http://fonts.gstatic.com/s/f/directory$paddedVersion.pb');
  }

....
}
```

**Comment by takinok** [comment]
TO: @material-admin 
I know we should update the font data of this package by ourselves according to the following. 
https://github.com/material-foundation/google-fonts-flutter/blob/develop/CONTRIBUTING.md#updating-the-fonts

But I couldn't as I posted first. Could you assign someone to this request?
 
This package is great and makes many developers happy. 
Regards,
