### ISSUE TITLE
[BUG] Tried loading the staatliches font on a flutter desktop app and can't do so.

### ISSUE THREAD

**Issue by wildaces215** [material-foundation/google-fonts-flutter#178]
**To Reproduce**
1. Call google_fonts package `import 'package:google_fonts/google_fonts.dart';`
2. Call the font from the GoogleFonts object and place inside the Text Widget parameter styling 
`Text('Crypto App', style: GoogleFonts.staatliches())`
3. See photo for error

**Expected behavior**
Expected to load the font when called.

**Screenshots**

![image](https://user-images.githubusercontent.com/13178401/130371913-82c198ae-ad4a-4aa1-8951-4ab119f0149c.png)
Device: Macbook Pro Desktop running Big Sur

**Comment by bmsrangel** [comment]
I'm facing this same issue. I tried other fonts as well, and I have the same result. I'm using a MacBook Pro (13-inch, M1, 2020) running macOS Big Sur version 11.5.2

![image](https://user-images.githubusercontent.com/39227201/132753308-1a3bd279-8d91-42ff-aed3-c2c2881cd0ba.png)

My flutter doctor -v:
```
[✓] Flutter (Channel stable, 2.5.0, on macOS 11.5.2 20G95 darwin-arm, locale
    pt-BR)
    • Flutter version 2.5.0 at /Users/bmsrangel/src/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (2 days ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/bmsrangel/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.60.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 11.5.2 20G95 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 93.0.4577.63

• No issues found!```

**Comment by mrunion** [comment]
Try adding the permission to allow the networking client on MacOS.

Add:

```
<key>com.apple.security.network.client</key>
<true/>
```

to the **DebugProfile.entitlements** and **Release.entitlements** files in the _macOS > runner_ folder and see if it works now.

**Comment by bmsrangel** [comment]
> Try adding the permission to allow the networking client on MacOS.
> 
> Add:
> 
> ```
> <key>com.apple.security.network.client</key>
> <true/>
> ```
> 
> to the **DebugProfile.entitlements** and **Release.entitlements** files in the _macOS > runner_ folder and see if it works now.

Thank you, @mrunion! That worked perfectly!
