### ISSUE TITLE
[BUG] load license error

### ISSUE THREAD

**Issue by joshuafriso** [material-foundation/google-fonts-flutter#194]
**Describe the bug**
I recieve this message error "Flutter Error (Unable to load asset: google_fonts/OFL.txt)" everytime the project try to execute the load.

LicenseRegistry.addLicense(() async* {
    final license = await rootBundle.loadString('google_fonts/OFL.txt');
    yield LicenseEntryWithLineBreaks(['google_fonts'], license);
  });

Is it need any other configuration?

**Comment by guidezpl** [comment]
Hi, that file needs to exist, and you should add it to your [assets](https://api.flutter.dev/flutter/services/rootBundle.html). Please re-open if it still doesn't work!
