### ISSUE TITLE
[BUG] Poppins is wrong! Flutter is using an old(?) version of the font.

### ISSUE THREAD

**Issue by bernaferrari** [material-foundation/google-fonts-flutter#199]
Poppins has wrong ‘?’ (possibly a previous font version?!). Debugged by intercepting the call.

![image](https://user-images.githubusercontent.com/351125/146627029-27494341-958c-41b8-8381-3982401b6f43.png)

DartPad: 
https://dartpad.dev/?id=3640b6eb43e760fd88d10fb22aea90e5
Codepen:
https://codepen.io/bernardoferrari/pen/LYzyXKW?editors=1100
Diff (exactly same spacing, everything is the same, code copied from Flutter web renderer):
![image](https://user-images.githubusercontent.com/351125/146627219-3b51cd7d-50c9-4e1f-aca0-00b36f8ea465.png)

**Comment by devj3ns** [comment]
This sounds similar to an issue I created a while ago.

Have a look at [#163](https://github.com/material-foundation/google-fonts-flutter/issues/163).

In found out that the font weight is different when you use the flutter plugin compared to downloading the font manually from Google fonts and import it locally.

**Comment by bernaferrari** [comment]
In this case it is not only the FontWeight but the font itself. See how "?" changes between Flutter and the official Google Fonts font.

**Comment by guidezpl** [comment]
Internal bug is b/212679312
