### ISSUE TITLE
[BUG] Nunito font from package google_fonts 2.1.1 didn't display Cyrillic correctly

### ISSUE THREAD

**Issue by Alexqwesa** [material-foundation/google-fonts-flutter#207]
**Describe the bug**
Nunito font from package google_fonts 2.1.1 didn't display Cyrillic correctly

**To Reproduce**
1. add google_fonts to project
2. use code below (text with nunito font)
3. See Cyrillic symbols in some other font (not nunito)

for comparison i tried lobster font (with same settings) - it works as expected

[https://github.com/Alexqwesa/test_task_pizza_shop_project/blob/master/lib/bug_screen.dart](https://github.com/Alexqwesa/test_task_pizza_shop_project/blob/master/lib/bug_screen.dart)

```
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

class BugScreen extends StatefulWidget {
  const BugScreen({Key? key}) : super(key: key);

  @override
  _BugScreenState createState() => _BugScreenState();
}

class _BugScreenState extends State<BugScreen> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      // resizeToAvoidBottomInset: false,
      body: SizedBox.expand(
        child: Column(
          children: [
            const Divider(
              thickness: 10,
            ),
            const Text(
              ' Регистрация Nunito(font from asset) - it works',
              style: TextStyle(
                fontFamily: 'NunitoAsset',
                fontSize: 50,
                fontWeight: FontWeight.w800,
                color: Colors.black,
              ),
            ),
            const Divider(
              thickness: 10,
            ),
            Text(
              'Регистрация Nunito - did not work',
              style: GoogleFonts.nunito(
                // this didn't work
                textStyle: const TextStyle(
                  fontSize: 50,
                  fontWeight: FontWeight.w800,
                  color: Colors.black,
                ),
              ),
            ),
            const Divider(
              thickness: 10,
            ),
            Text(
              'Регистрация Lobster(font from GoogleFonts) - the same config works',
              style: GoogleFonts.lobster(
                // this works!!!!
                textStyle: const TextStyle(
                  fontSize: 50,
                  fontWeight: FontWeight.w800,
                  color: Colors.black,
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

```

**Expected behavior**
Cyrillic symbols should be displayed in nanito font than i use nanito font from package google_fonts 2.1.1

**Screenshots**
![font bug](https://user-images.githubusercontent.com/48125025/147732795-865db4a5-1f0b-4a2a-86f1-fa530e96ec25.png)
[https://github.com/Alexqwesa/test_task_pizza_shop_project/blob/master/lib/screenshot_of_font_bug.png](https://github.com/Alexqwesa/test_task_pizza_shop_project/blob/master/lib/screenshot_of_font_bug.png)

**Smartphone (please complete the following information if applicable):**
 - any

**Comment by guidezpl** [comment]
Correct me if I'm wrong, but it looks to be rendering the same font, just at a different font weight. Does #163 answer your question?

**Comment by Alexqwesa** [comment]
> Correct me if I'm wrong, but it looks to be rendering the same font, just at a different font weight. Does #35 answer your question?

Yes, i have that bug too,

**But this is a different bug, as you can see in the image bellow:**

- on left side there is a four letter in Nanito style(two english and two cyrillic), 
- on the other site there two of four characters in nanito style(english), and two other characters(cyrilic) in some different font

![Screenshot_20211230_222619](https://user-images.githubusercontent.com/48125025/147782449-f18af726-3327-4385-af17-f4dd95ce44da.png)

**Comment by vanyasem** [comment]
This bug seems to affect https://fonts.google.com/specimen/Great+Vibes as well
