### ISSUE TITLE
[Bug] Wrong name on Noto Sans Japanese

### ISSUE THREAD

**Issue by takinok** [material-foundation/google-fonts-flutter#210]
Thank you for font updating! I really appreciate it.

However, I found the following a bug on the Noto Sans Japanese.
Unfortunately the wrong name "Noto Sans Javanese" is added on #206 . "Noto Sans Japanese" is the correct font name.

**Comment by guidezpl** [comment]
Of course! The font is correct, it is https://fonts.google.com/noto/specimen/Noto+Sans+Javanese. Noto Sans Japanese will be added. Follow #126 for updates
