### ISSUE TITLE
NunitoSans font from package google_fonts 2.2.0 does not look right

### ISSUE THREAD

**Issue by srdjan86** [material-foundation/google-fonts-flutter#211]
## Steps to Reproduce

- add google_fonts to project
- use code below (text with NunitoSans font)

**Expected results:** [NunitoSans Google fonts](https://fonts.google.com/specimen/Nunito+Sans#standard-styles)
<img width="1470" alt="Screenshot 2022-01-11 at 10 41 40" src="https://user-images.githubusercontent.com/48443262/148918690-2dc56275-83f4-40a2-84ba-dfb2b0a8cd14.png">

**Actual results:** 
![Simulator Screen Shot - iPhone 13 - 2022-01-11 at 10 34 45](https://user-images.githubusercontent.com/48443262/148918864-53053496-93ea-4c0b-b98e-c1ced6b57c67.png)

```dart
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

class TestPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Text(
          'Almost before we knew it, we had left the ground.',
          style: GoogleFonts.nunitoSans(),
        ),
      ),
    );
  }
}
```

**Comment by guidezpl** [comment]
There's probably an error in the run logs. Can you provide the output of `flutter run -v`?

**Comment by srdjan86** [comment]
[log.txt](https://github.com/material-foundation/google-fonts-flutter/files/7846588/log.txt)

**Comment by guidezpl** [comment]
Thanks, I'm seeing that the font is applied but the look doesn't match the website's look, possible that we just need to update the font on the backend
