### ISSUE TITLE
All letters are capitalise 

### ISSUE THREAD

**Issue by mfkk16** [material-foundation/google-fonts-flutter#212]
Whwn i using "Bebas Neue" font all letters are capitalise. I need only first letter are capitalise.

**Comment by clocksmith** [comment]
Hi, that is the intended style of the font: https://fonts.google.com/?query=bebas

Suggestion: Try using multiple `Text` or `TextSpan` https://api.flutter.dev/flutter/painting/TextSpan-class.html
and increase the font size of the letter you want capitalized to create an illusion of a capitalized letter if you want to use this font with captials.
