### ISSUE TITLE
IBM Plex Sans Arabic  from google fonts is not included here

### ISSUE THREAD

**Issue by TariqHattab** [material-foundation/google-fonts-flutter#213]
Hello, I can't find IBM Plex Sans Arabic, even after I updated to the latest version, I think it was added to fonts.google.com 25 days ago, did I miss it? is there a way for me to add it if it is not included?  Thank you very much.

**Comment by guidezpl** [comment]
I'm seeing it as available with 2.2.0
<img width="595" alt="Screenshot 2022-01-30 at 17 37 12" src="https://user-images.githubusercontent.com/6655696/151708443-5d91dc2f-3f4a-493c-9672-11bde5560419.png">
 
Can you double check your pubspec and please re-open if necessary?
