### ISSUE TITLE
No named parameter with the name 'displayLarge'.       displayLarge: this issue is arising after new update

### ISSUE THREAD

**Issue by aryant-nigam** [material-foundation/google-fonts-flutter#218]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by guidezpl** [comment]
This version requires the current stable release of Flutter 2.10 or later. You can either upgrade with `flutter upgrade` (recommended), or pin the package in your `pubspec.yaml` with `google_fonts: 2.2.0`.

I'll publish an update shortly bumping up the required Flutter SDK so the error is clearer.

**Comment by wafutech** [comment]
I am having exactly issue. I am using Flutter 2.12 and google_fonts: 2.2.0. My App was working just well  but it crashed with same error. I am tried to upgrade to google_fonts 2.3.0 without luck.

**Comment by guidezpl** [comment]
Can you share your pubspec and `flutter doctor -v`?

**Comment by RoyalCoder88** [comment]
Just upgrade flutter SDK to the new version above >2.10 will solve the issue
