### ISSUE TITLE
Error: No named parameter with the name 'displayLarge'.

### ISSUE THREAD

**Issue by lafskelton** [material-foundation/google-fonts-flutter#219]
## Steps to Reproduce

Using GoogleFonts 2.3.0 in flutter web with 
`... child: Text("jhfsd", style: GoogleFonts.*any*(),` 
anywhere in the tree causes this issue 

Cmd: 
`flutter run -d Chrome`

Output: 
`
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/google_fonts-2.3.0/lib/google_fonts.dart:141202:7:     
Error: No named parameter with the name 'displayLarge'.
      displayLarge:
      ^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/material/text_theme.dart:81:9: Context: Found this candidate, but
the arguments don't match.
  const TextTheme({
        ^^^^^^^^^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/google_fonts-2.3.0/lib/google_fonts.dart:141332:7:     
Error: No named parameter with the name 'displayLarge'.
      displayLarge:
      ^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/material/text_theme.dart:81:9: Context: Found this candidate, but
the arguments don't match.
  const TextTheme({
        ^^^^^^^^^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/google_fonts-2.3.0/lib/google_fonts.dart:141427:7:     
Error: No named parameter with the name 'displayLarge'.
      displayLarge: GoogleFonts.zenKurenaido(textStyle: textTheme.displayLarge),
      ^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/material/text_theme.dart:81:9: Context: Found this candidate, but
the arguments don't match.
  const TextTheme({
        ^^^^^^^^^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/google_fonts-2.3.0/lib/google_fonts.dart:141525:7:     
Error: No named parameter with the name 'displayLarge'.
      displayLarge: GoogleFonts.zenLoop(textStyle: textTheme.displayLarge),
      ^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/material/text_theme.dart:81:9: Context: Found this candidate, but
the arguments don't match.
  const TextTheme({
        ^^^^^^^^^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/google_fonts-2.3.0/lib/google_fonts.dart:141640:7:     
Error: No named parameter with the name 'displayLarge'.
      displayLarge:
      ^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/material/text_theme.dart:81:9: Context: Found this candidate, but
the arguments don't match.
  const TextTheme({
        ^^^^^^^^^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/google_fonts-2.3.0/lib/google_fonts.dart:141747:7:     
Error: No named parameter with the name 'displayLarge'.
      displayLarge: GoogleFonts.zenOldMincho(textStyle: textTheme.displayLarge),
      ^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/material/text_theme.dart:81:9: Context: Found this candidate, but
the arguments don't match.
  const TextTheme({
        ^^^^^^^^^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/google_fonts-2.3.0/lib/google_fonts.dart:141838:7:     
Error: No named parameter with the name 'displayLarge'.
      displayLarge: GoogleFonts.zenTokyoZoo(textStyle: textTheme.displayLarge),
      ^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/material/text_theme.dart:81:9: Context: Found this candidate, but
the arguments don't match.
  const TextTheme({
        ^^^^^^^^^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/google_fonts-2.3.0/lib/google_fonts.dart:141929:7:     
Error: No named parameter with the name 'displayLarge'.
      displayLarge: GoogleFonts.zeyada(textStyle: textTheme.displayLarge),
      ^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/material/text_theme.dart:81:9: Context: Found this candidate, but
the arguments don't match.
  const TextTheme({
        ^^^^^^^^^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/google_fonts-2.3.0/lib/google_fonts.dart:142016:7:     
Error: No named parameter with the name 'displayLarge'.
      displayLarge: GoogleFonts.zhiMangXing(textStyle: textTheme.displayLarge),
      ^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/material/text_theme.dart:81:9: Context: Found this candidate, but
the arguments don't match.
  const TextTheme({
        ^^^^^^^^^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/google_fonts-2.3.0/lib/google_fonts.dart:142170:7:     
Error: No named parameter with the name 'displayLarge'.
      displayLarge: GoogleFonts.zillaSlab(textStyle: textTheme.displayLarge),
      ^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/material/text_theme.dart:81:9: Context: Found this candidate, but
the arguments don't match.
  const TextTheme({
the arguments don't match.
  const TextTheme({
        ^^^^^^^^^

`

**Comment by guidezpl** [comment]
This version requires the current stable release of Flutter 2.10 or later. You can either upgrade with `flutter upgrade` (recommended), or pin the package in your `pubspec.yaml` with `google_fonts: 2.2.0`.

I'll publish an update shortly bumping up the required Flutter SDK so the error is clearer.

**Comment by MrKhay** [comment]
Awesome solution works perfectly

**Comment by AhmedHammad0900** [comment]
> This version requires the current stable release of Flutter 2.10 or later. You can either upgrade with `flutter upgrade` (recommended), or pin the package in your `pubspec.yaml` with `google_fonts: 2.2.0`.
> 
> I'll publish an update shortly bumping up the required Flutter SDK so the error is clearer.

I am on flutter Stable 2.10 google_fonts didn't work on 2.2.0 or 2.3.0 and still have the same problem


![image](https://user-images.githubusercontent.com/81931290/152734991-5b82a3ec-9787-4120-b627-9a7d3878c806.png)

**Comment by interpre** [comment]
Just want to mention that it should not have ^ in `google_fonts: 2.2.0`
It might save a lot of time to others.

**Comment by hpchari** [comment]
This error occurs when the integrated packages or you have used older version of [google_fonts](https://pub.dev/packages/google_fonts) package. To solve this error, add google_fonts package with the latest version. For example:

`dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^2.3.1`

Source: [Solution: Error: No named parameter with the name ’displayLarge’](https://www.fluttercampus.com/guide/272/error-no-named-parameter-with-the-name-displaylarge/)

**Comment by kishanSindhi** [comment]
remove ^ from the dependency of google_fonts (it worked for me)
