### ISSUE TITLE
Font size issue with some fonts

### ISSUE THREAD

**Issue by LinusMuema** [material-foundation/google-fonts-flutter#220]
I believe there are some fonts, or at least one that has some design issues.

The `GoogleFonts.dongle(fontSize: 15)` font adds some extra padding to the text fields and the font size doesn't really match. The text is really small and the sometimes the weight is also not applied. Unlike other fonts like `GoogleFonts.poppins(fontSize: 15)` and `GoogleFonts.nunito(fontSize: 15)` which apply the styles accordingly.

Screenshots demonstrating this below.
![dongle](https://user-images.githubusercontent.com/47350130/154066622-b30140f7-70d4-4f54-a6f9-c257167ff85f.png)
![poppins](https://user-images.githubusercontent.com/47350130/154066656-95b112eb-61ad-43bf-a476-2d85936e9c2a.png)

**Comment by clocksmith** [comment]
This looks like an issue with a a Font specifically, and not the Google Fonts Flutter package, please redirect this issue with https://github.com/google/fonts

One way to repro would be to not use Google Fonts Flutter package, and import the fonts manually, and see if the spacing is still an issue.

Closing for now, but please re-open if its an issue with this package
