### ISSUE TITLE
support obfuscation - proper serialisation of FontStyle

### ISSUE THREAD

**Issue by daadu** [material-foundation/google-fonts-flutter#222]
https://github.com/material-foundation/google-fonts-flutter/blob/3e6361869cc09173aed63334f80bc91aa0d4105c/lib/src/google_fonts_variant.dart#L116-L120

**Comment by clocksmith** [comment]
Hi thanks for filing this bug, could you please elaborate with an example of why the serializing is improper?

**Comment by daadu** [comment]
@clocksmith usage of `FontStyle.toString()` will not be the same when code is obfuscated.

Check "Caveat" section here - https://docs.flutter.dev/deployment/obfuscate#caveat

**Comment by daadu** [comment]
Ok, I see.,`FontStyle` is not a enum (I assumed it, my bad.) instead is a class with proper `toString` implementation.

Closing this issue.
