### ISSUE TITLE
Fredoka font is missing

### ISSUE THREAD

**Issue by areee** [material-foundation/google-fonts-flutter#223]
It seems that [Fredoka](https://fonts.google.com/specimen/Fredoka) is not included in static methods, although the older "downgrade" version [Fredoka One](https://fonts.google.com/specimen/Fredoka+One) is already there.

**Comment by cybertheory** [comment]
Please see this link for more info: https://github.com/material-foundation/google-fonts-flutter/blob/5fb2c69fbc430bf0549b4299a01f8d324947cb00/CONTRIBUTING.md

**Comment by cybertheory** [comment]
and this issue:
https://github.com/material-foundation/google-fonts-flutter/issues/126
