### ISSUE TITLE
Smooch sans font missing

### ISSUE THREAD

**Issue by michaelromero** [material-foundation/google-fonts-flutter#225]
[Smooch Sans](https://fonts.google.com/specimen/Smooch+Sans) is missing unfortunately. Smooch is there.

**Comment by cybertheory** [comment]
Please see this link for more info: https://github.com/material-foundation/google-fonts-flutter/blob/5fb2c69fbc430bf0549b4299a01f8d324947cb00/CONTRIBUTING.md

**Comment by cybertheory** [comment]
and this issue:
https://github.com/material-foundation/google-fonts-flutter/issues/126
