### ISSUE TITLE
Twinkle star font is missing

### ISSUE THREAD

**Issue by Tom3652** [material-foundation/google-fonts-flutter#226]
[Twinkle star](https://fonts.google.com/specimen/Twinkle+Star?query=Twinkle+star) font is also missing

**Comment by cybertheory** [comment]
Please see this link for more info: https://github.com/material-foundation/google-fonts-flutter/blob/5fb2c69fbc430bf0549b4299a01f8d324947cb00/CONTRIBUTING.md

**Comment by cybertheory** [comment]
and this issue:
https://github.com/material-foundation/google-fonts-flutter/issues/126
