### ISSUE TITLE
Google font fails to load 

### ISSUE THREAD

**Issue by pravinhalady** [material-foundation/google-fonts-flutter#250]
- Tried to run codelab:  https://codelabs.developers.google.com/codelabs/flutter-boring-to-beautiful#3
- Montserrat font fails to load while running in gphone emulator, though google_fonts included in dependencies, and AndroidManifest.xml has correct perms (see attached files)

[AndroidManifestxml.pdf](https://github.com/material-foundation/google-fonts-flutter/files/8790040/AndroidManifestxml.pdf)
[pubspec_yaml.pdf](https://github.com/material-foundation/google-fonts-flutter/files/8790041/pubspec_yaml.pdf)
[google_font_error.pdf](https://github.com/material-foundation/google-fonts-flutter/files/8790042/google_font_error.pdf)

**Comment by guidezpl** [comment]
I think your emulator may not be connected to the internet. See https://stackoverflow.com/questions/42736038/android-emulator-not-able-to-access-the-internet

**Comment by ajinkya446** [comment]
**It needs the internet to load the font asset from the server. When you connected to the internet it will resolve your issue.**

**Comment by esouthren** [comment]
Marking as closed - please let us know if you continue having issues, @pravinhalady. Thank you!
