### ISSUE TITLE
Flutter 3: Google Font Roboto Flex bold weight issue . Shows thinner fonts 

### ISSUE THREAD

**Issue by sakthiv441** [material-foundation/google-fonts-flutter#263]
## Steps to Reproduce

Use Roboto Flex font From Google_font Package in a normal text widget with bold font wight and render in android with Flutter 3.

1. Execute `flutter run` on the code sample 
2. Flutter does not render bold fonts properly for robotoFlex Fonts . It create a huge impact in Ui  
3. I tried comparing with other fonts . Other fonts render properly you can see lato fonts render perfectly in the comparison . And also tried downloading font from google fonts as ttf and added as custom font in font library. It doesn't change any result

**Expected results:** ![image](https://user-images.githubusercontent.com/106237590/190566765-82c066c1-1c76-4a48-ba24-a2ab4c80cb6b.png)

**Actual results:** <![Screenshot 2022-09-16 110544](https://user-images.githubusercontent.com/106237590/190566957-1d0e734e-504f-4af0-85c5-aff2d7c74b50.png)>

<details>
<summary>Code sample</summary>

 Center(
                                  child: Text(
                                    'GoogleFonts.lato',
                                    style: GoogleFonts.lato(
                                        textStyle: const TextStyle(
                                      fontSize: 17,
                                    )),
                                  ).pV(5).pH(20),
                                ),
                                Center(
                                  child: Text(
                                    'This is GoogleF.lato',
                                    style: GoogleFonts.lato(
                                        textStyle: const TextStyle(
                                            fontSize: 26,
                                            fontWeight: FontWeight.w900)),
                                  ).pV(5).pH(20),
                                ),
                                Center(
                                  child: Text(
                                    'This is GoogleF.lato',
                                    style: GoogleFonts.lato(
                                        textStyle: const TextStyle(
                                            fontSize: 26,
                                            fontWeight: FontWeight.bold)),
                                  ).pV(1).pH(20),
                                ),
                                const SizedBox(
                                  height: 35,
                                ),
                                Center(
                                  child: Text(
                                    'GoogleFonts.robotoflex',
                                    style: GoogleFonts.robotoFlex(
                                        textStyle: const TextStyle(
                                      fontSize: 17,
                                    )),
                                  ).pV(5).pH(20),
                                ),
                                Center(
                                  child: Text(
                                    'This is GoogleF.RobotoFlex',
                                    style: GoogleFonts.robotoFlex(
                                        textStyle: const TextStyle(
                                            fontSize: 26,
                                            fontWeight: FontWeight.w900)),
                                  ).pV(1).pH(20),
                                ),

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

 Flutter (Channel beta, 3.3.0-0.5.pre, on Microsoft Windows [Version 10.0.22000.978],
    locale en-IN)
    • Flutter version 3.3.0-0.5.pre on channel beta at C:\Users\ASUS\Development\sdks\flutter 
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 096162697a (3 weeks ago), 2022-08-22 15:34:14 -0700
    • Engine revision ad3d868e0d
    • Dart version 2.18.0 (build 2.18.0-271.7.beta)
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\ASUS\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default
      components

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] VS Code (version 1.71.2)
    • VS Code at C:\Users\ASUS\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.48.0

[√] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 12 (API 31)     
      (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows
      [Version 10.0.22000.978]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome
      105.0.5195.126
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge
      105.0.1343.33

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```
```

</details>

**Comment by guidezpl** [comment]
I think you need to pass the weight in the `lato` constructor to get the right font file.

**Comment by guidezpl** [comment]
Try
```
GoogleFonts.lato(
  fontWeight: FontWeight.w900
  textStyle: const TextStyle(
    fontSize: 26,
  ),
),
```

instead of 

```
GoogleFonts.lato(
  textStyle: const TextStyle(
  fontSize: 26,
  fontWeight: FontWeight.w900),
),
```

**Comment by sakthiv441** [comment]
What should I do now ?

**Comment by guidezpl** [comment]
Please ask a support forum (e.g. StackOverflow, Discord, Reddit) for more help. GitHub issues are meant for feature requests and bug reports.

**Comment by prkhrv** [comment]
@sakthiv441 Did you find any solution?

**Comment by ManhBanh** [comment]
@sakthiv441 Did you have any way to fix it?
