### ISSUE TITLE
`Noto Color Emoji Compat` removed

### ISSUE THREAD

**Issue by mursalov** [material-foundation/google-fonts-flutter#267]
`Noto Color Emoji Compat` seems to have been removed with version 3.0.0 and I think this is very unfortunate since it was the only font that provided colorful emojis. I am curious about the reason behind its removal and wanted to ask if it is possible to have it back in the next version?

**Comment by guidezpl** [comment]
Thanks for raising this. Since it is still available on fonts.google.com, we should also make it available. I asked the question internally (b/212601535) and will follow-up.

**Comment by guidezpl** [comment]
An update is planned in the coming weeks to add it back, I'll have more info then.

**Comment by TesteurManiak** [comment]
Great thanks!

**Comment by sashkyn** [comment]
I will wait it too :)

**Comment by guidezpl** [comment]
Right now :) https://pub.dev/packages/google_fonts

**Comment by sashkyn** [comment]
Wow!!!! Great
