### ISSUE TITLE
I/flutter (30926): Error: google_fonts was unable to load font Nunito-Regular because the following exception occurred: I/flutter (30926): Exception: Failed to load font with url: https://fonts.gstatic.com/s/a/e80eb162b059ec70c9d813608a8ca309960098918ec1b6efad8776440dc20760.ttf

### ISSUE THREAD

**Issue by al-mohad** [material-foundation/google-fonts-flutter#269]
E/flutter (30926): #2      _MapStream._handleData (dart:async/stream_pipe.dart:213:31)
E/flutter (30926): #3      _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
E/flutter (30926): #4      _RootZone.runUnaryGuarded (dart:async/zone.dart:1586:10)
E/flutter (30926): #5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (30926): #6      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter (30926): #7      _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123:11)
E/flutter (30926): #8      _MapStream._handleData (dart:async/stream_pipe.dart:218:10)
E/flutter (30926): #9      _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
E/flutter (30926): #10     _RootZone.runUnaryGuarded (dart:async/zone.dart:1586:10)
E/flutter (30926): #11     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (30926): #12     _DelayedData.perform (dart:async/stream_impl.dart:515:14)
E/flutter (30926): #13     _PendingEvents.handleNext (dart:async/stream_impl.dart:620:11)
E/flutter (30926): #14     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591:7)
E/flutter (30926): #15     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter (30926): #16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
E/flutter (30926):

**Comment by guidezpl** [comment]
Without more info (code, platform, OS, version, etc.), this is unactionable, closing.
