### ISSUE TITLE
Unable to find modules

### ISSUE THREAD

**Issue by cytryn** [material-foundation/google-fonts-flutter#36]
So I tried to add the package on a very simple web project, I added the dependency on the yaml file, added the import and used on a text style.

No errors show up on VSCode but when I run, I get the following error msg on debug console:

> Unable to find modules for some sources, this is usually the result of either a
> bad import, a missing dependency in a package (or possibly a dev_dependency
> needs to move to a real dependency), or a build failure (if importing a
> generated file).
> 
> Please check the following imports:
> 
> import 'package:google_fonts/google_fonts.dart'; from myproject|lib/widgets/hero.dart at 2:1
> 
> Failed after 127ms

Is there any known issue on using the package for Flutter for Web?

**Edit1:** I didn't do anything related to font's but the error does not show up anymore. But the font's also don't load. I tried to use direct style on Text() and also applying to a Theme, none worked. Also, when I start the project, my debugger stops like 3 times before loading the page... I have to manually press play on VSCode for it to show up.

**Eidt2:** I realized the debugger stop every time there is a call to GoogleFonts like `Text('trying with Raleway', style: GoogleFonts.raleway())`. But nothing show up on debug console.

**Comment by clocksmith** [comment]
It looks like the original issue filed here has been worked out. Could you please file a separate issue for the debugging issue you are having, if it still exists?
