### ISSUE TITLE
Where are font examples? I've tried fonts.google.com but I need to download stuff

### ISSUE THREAD

**Issue by emailsubjekt** [material-foundation/google-fonts-flutter#39]
Where can I see the list of default fonts inside this library that I can use and not download like in the linked webpage https://fonts.google.com/, but use directly from the library. I can see I can choose a lot of them but then I have to reload each time, is there a list someplace where I can see all the options? Thanks

**Comment by clocksmith** [comment]
Hi, https://fonts.google.com/ is currently the best way to see examples or previews of the font you intend to use
