### ISSUE TITLE
The offline fonts option does not work in example

### ISSUE THREAD

**Issue by atreeon** [material-foundation/google-fonts-flutter#49]
If you run the example, the font in this bit of code
```
Text(
  '$_counter', 
  style: GoogleFonts.lato(fontStyle: FontStyle.italic),
```
is not lato (it is italic, it is a bit difficult to tell without increasing the font size and comparing it to the default).  It seems any font that has been included in the google_fonts directory shows the incorrect font.

If you add the following code
```
            Text(
              '$_counter',
              style:
                  GoogleFonts.lato(fontStyle: FontStyle.italic, fontSize: 50),
            ),
            Text(
              '$_counter',
              style: TextStyle(fontStyle: FontStyle.italic, fontSize: 50),
            ),
```

the fonts look identical if retrieving the fonts from the google_fonts directory

<img width="117" alt="Screenshot 2020-01-09 at 10 47 15" src="https://user-images.githubusercontent.com/4139336/72061352-994f0a80-32cd-11ea-8461-14ba2cf7cd32.png">

and if you comment this assets google_fonts in the pubspec.yaml

```
#  assets:
#    - google_fonts/
```

the fonts look different, as the should, when loading from http (difficult to spot still but the '0' is fatter on the first one...ie it is lato as it should be)

<img width="139" alt="Screenshot 2020-01-09 at 10 46 20" src="https://user-images.githubusercontent.com/4139336/72061408-b7b50600-32cd-11ea-862f-806ec4dac48b.png">

**Comment by clocksmith** [comment]
Can you please list the contents of your `google_fonts` folder? If it includes `Lato-Italic.ttf`, then we may have a bug with offline loading.

**Comment by atreeon** [comment]
Yes, it does include that font

**Comment by johnsonmh** [comment]
This should have been fixed as of `0.3.7`. Can you `flutter pub update` and see if you still have the issue?

**Comment by Braj65** [comment]
I am on 1.1.0 version and i am facing something similar. At project level i have assets/google_fonts/Lemonada-Regular.ttf. In pubspec.yaml
assets:
  - assets/google_fonts/
And in main.dart - 
       Text(
              'You have pushed the button this many times:',
              style: GoogleFonts.getFont('Lemonada'),
            ),
The app is running offline and the text is not appearing in Lemonada font.

**Comment by papmodern** [comment]
I also have the weight problem

**Comment by guidezpl** [comment]
@papmodern Can you please file a new issue with all required information? Thanks!
