### ISSUE TITLE
Having trouble loading the Sniglet font

### ISSUE THREAD

**Issue by AbdullahNauman** [material-foundation/google-fonts-flutter#51]
Hi, 

I am new to building apps with flutter and came across this API as an easy way to add fonts to the app without downloading the different assets. I am currently trying to load the Sniglet font, but seem to be getting an error. 

Here's my code: 

`  "Hi there,",
                    style: GoogleFonts.Sniglet(
                        fontWeight: FontWeight.bold,
                        fontSize: 35.0,
                        color: color),
                  ),` 
This is the error that I am getting: 

> The method 'Sniglet' isn't defined for the class 'GoogleFonts'.
> Try correcting the name to the name of an existing method, or defining a method named 'Sniglet'.dart(undefined_method)
> 

I checked the [fonts_data.json](https://github.com/material-foundation/google-fonts-flutter/blob/master/data/fonts_data.json) file, and Sniglet seems to be listed there. Am I using it wrong? Could someone please point me in the right direction? 

Thank in advance. Please let me know if you need anything else.

**Comment by clocksmith** [comment]
Hi, it looks like this font does exist, but the capitalization is off. It should be with a lowercase s instead of an uppercase S: `GoogleFonts.sniglet(...)`
