### ISSUE TITLE
Save font files in `Support` instead of `Documents` directory

### ISSUE THREAD

**Issue by Cisneiros** [material-foundation/google-fonts-flutter#52]
Right now, Google Fonts Flutter stores downloaded fonts using Path Provider's `getApplicationDocumentsDirectory` ([as seen here](https://github.com/material-foundation/google-fonts-flutter/blob/7ca76f6dae04d2ffb211b9f3f547a996eef05b5b/lib/src/google_fonts_base.dart#L200-L203)). When an application is a Document application (at least in iOS), this whole directory is exposed to the end user, and having the fonts there is not ideal as it is supposed to contain, as the name suggests, `Documents` from your app.

Path Provider also supplies a `getApplicationSupportDirectory` function ([documented here](https://pub.dev/documentation/path_provider/latest/path_provider/getApplicationSupportDirectory.html)), which is supported on iOS and Android, and the docs read:

> Path to a directory where the application may place application support files.
>
>Use this for files you don’t want exposed to the user. Your app should not use this directory for user data files.

This seems ideal for storing this kind of file. They are backed up and persistent on iOS as app data, just as with the Documents directory. I'm happy to send a PR for this, but just wanted to know if there is any other reasoning behind storing fonts in the Documents app directory, so I opened this issue.

**Comment by clocksmith** [comment]
On `path_provider`,  `getTemporaryDirectory()` should be used for the place to write our font files to

**Comment by Cisneiros** [comment]
I figured we'd use the `Support` one so the fonts are persisted (same as the `Documents` directory today), and not cleaned up by the OS eventually. But if you believe it makes sense to add them to a temp directory instead, I can update my PR #53
