### ISSUE TITLE
Offline fonts aren't working

### ISSUE THREAD

**Issue by Reprevise** [material-foundation/google-fonts-flutter#54]
I have created a folder `google_fonts` at the top of my project and imported it in my `pubspec.yaml` class. When I build the apk, all of my fonts default to Roboto but I have different fonts specified throughout my Dart classes.

**Comment by clocksmith** [comment]
Can you please send an example of how the fonts are specified? Also, can you share the contents of your google_fonts folder?

**Comment by Reprevise** [comment]
Sure!

Here's a screenshot of my `google_fonts` folder.
![google_fonts folder](https://user-images.githubusercontent.com/25782944/72832891-b8e21d80-3c53-11ea-8a48-aee7f44acfe9.png)

Here's a snippet of how the fonts are used (they're used in more files too, this is just where all of them are used in one file).
```dart
    body1: GoogleFonts.rubik(
      textStyle: const TextStyle(
        color: Colors.black,
      ),
    ),
    body2: GoogleFonts.muli(
      fontWeight: FontWeight.bold,
      textStyle: const TextStyle(
        color: Colors.black,
      ),
    ),
    button: GoogleFonts.openSans(
      fontWeight: FontWeight.bold,
      textStyle: const TextStyle(color: Colors.black),
    ),
    display1: GoogleFonts.muli(
      fontSize: 15.0,
      fontWeight: FontWeight.bold,
      textStyle: const TextStyle(
        letterSpacing: 0.3,
        color: Colors.black,
      ),
    ),
```

I have my repo ([school_life](https://github.com/Reprevise/school_life)) if you want to see how they are used completely.

**Comment by firatagdas** [comment]
I can confirm that, I 'm having the exact issue.

**Comment by WhiteNazguls** [comment]
Yeah, same problem here..

**Comment by jeroen-meijer** [comment]
Same problem here.

@firatagdas @hansels Remember to 👍 the issue. Makes it easier for the team to see which issues most people are having trouble with.

**Comment by clocksmith** [comment]
This should have been fixed as of 0.3.7. Can you `flutter pub update` and see if you still have the issue?

**Comment by Reprevise** [comment]
I no longer experience the issue.

**Comment by jeroen-meijer** [comment]
I've resorted to using local fonts for other reasons.

To people reading this later, @clocksmith probably meant `flutter pub upgrade` 🙂
