### ISSUE TITLE
Try correcting the name to the name of an existing method, or defining a method named 'handleSystemMessage'.   PaintingBinding.instance.handleSystemMessage({'type': 'fontsChange'});

### ISSUE THREAD

**Issue by newtonmunene99** [material-foundation/google-fonts-flutter#6]
Compiler message:                                                       
../../../flutter/.pub-cache/hosted/pub.dartlang.org/google_fonts-0.1.1/lib/src/google_fonts_base.dart:105:28: Error: The method 'handleSystemMessage' isn't defined for the class 'PaintingBinding'.
 - 'PaintingBinding' is from 'package:flutter/src/painting/binding.dart' ('../../../flutter/packages/flutter/lib/src/painting/binding.dart').
Try correcting the name to the name of an existing method, or defining a method named 'handleSystemMessage'.
  PaintingBinding.instance.handleSystemMessage({'type': 'fontsChange'});
                           ^^^^^^^^^^^^^^^^^^^                          
Compiler failed on /home/munene/Projects/Flutter/echo/lib/main.dart

**Comment by codediodeio** [comment]
Also ran into this issue, running `flutter upgrade` fixed it.

**Comment by newtonmunene99** [comment]
@codediodeio what version of flutter are you running after flutter upgrade? It didn't work for me

**Comment by RafaelR7** [comment]
I´m having the same problem, my flutter version is STABLE v1.9.1+hotfix.6, I will change to the beta that way ahead, it is on v1.12.13+hotfix.5

**Comment by codediodeio** [comment]
I'm testing on Flutter `1.12.13+hotfix.5`, works on iOS/Android.

**Comment by RafaelR7** [comment]
the stable version was upgraded to `v1.12.13+hotfix.5` today,  I just upgrade my version everything is working now.

**Comment by newtonmunene99** [comment]
It's resolved after upgrading

**Comment by Sarps** [comment]
flutter upgrade worked for me too. Thanks @codediodeio

**Comment by AlvaroStudy** [comment]
I just ran flutter upgrade and all the working projects currently stopped working

**Comment by TEJESH5210** [comment]
> the stable version was upgraded to `v1.12.13+hotfix.5` today, I just upgrade my version everything is working now.

how to upgrade can u tell me

**Comment by TulioPintoNeto** [comment]
> > the stable version was upgraded to `v1.12.13+hotfix.5` today, I just upgrade my version everything is working now.
> 
> how to upgrade can u tell me

Just enter  the command "flutter upgrade" in your terminal console (check if you're in your correct folder application to do that)

**Comment by anantraj2808** [comment]
1. Run "flutter pub outdated". This will tell you all the outdated packages your project is using.
2. Then run "flutter pub upgrade --major-versions". This will upgrade all the outdated version.
This helped me.

**Comment by Deep052697** [comment]
Flutter Upgrade doesn't work, anyone have a different solution?

**Comment by Deep052697** [comment]
../.pub-cache/hosted/pub.dartlang.org/audio_service-0.17.1/lib/audio_service.dart:675:16: Error: The method 'setMockMethodCallHandler' isn't defined for the class 'MethodChannel'.
     - 'MethodChannel' is from 'package:flutter/src/services/platform_channel.dart' ('../Development/flutter/packages/flutter/lib/src/services/platform_channel.dart').
    Try correcting the name to the name of an existing method, or defining a method named 'setMockMethodCallHandler'.
                  .setMockMethodCallHandler(handler);
                   ^^^^^^^^^^^^^^^^^^^^^^^^
    ../.pub-cache/hosted/pub.dartlang.org/audio_service-0.17.1/lib/audio_service.dart:1266:68: Error: The method 'setMockMethodCallHandler' isn't defined for the class 'MethodChannel'.
     - 'MethodChannel' is from 'package:flutter/src/services/platform_channel.dart' ('../Development/flutter/packages/flutter/lib/src/services/platform_channel.dart').
    Try correcting the name to the name of an existing method, or defining a method named 'setMockMethodCallHandler'.
          MethodChannel('ryanheise.com/audioServiceBackgroundInverse').setMockMethodCallHandler(handler);

**Comment by anantraj2808** [comment]
> Flutter Upgrade doesn't work, anyone have a different solution?

Mentioned one possible solution above. Please check

**Comment by sushanmagar** [comment]
I had this issue while navigating to next page. 
Reason:- No automatic import.
Solution: - I imported the page manually.

**Comment by SezDeep** [comment]
Solved it by creating this functions then passing the image location/name
`Image image(String name) {
  return Image.asset(name);
}`

**Comment by dhanushkakavinda** [comment]
flutter upgrade is the perfect answer for this issue

**Comment by samvolton** [comment]
did not work, it does not get info from the class

**Comment by vikas960188** [comment]
> 1. Run "flutter pub outdated". This will tell you all the outdated packages your project is using.
> 2. Then run "flutter pub upgrade --major-versions". This will upgrade all the outdated version.
>    This helped me.

it is not working ..
