### ISSUE TITLE
Clarify the support for dark mode with an example in README

### ISSUE THREAD

**Issue by apgapg** [material-foundation/google-fonts-flutter#67]
The docs needs to be updated with correct syntax
```
 textTheme: GoogleFonts.latoTextTheme(
      ThemeData(brightness: Brightness.dark).textTheme,  //dark or white depends on usuage
    ),
```
With this the default text color in dark mode becomes white

**Comment by jesusrp98** [comment]
The `GoogleFont` class itself should be able to identify the current brightness property of the app, by `Theme.of(context).brightness`.

The solution exposed by @apgapg doesn't fix this issue.

**Comment by apgapg** [comment]
@jesusrp98 You have to use MediaQuery.of(context).platformBrightness to check if brightness light or dark

**Comment by jesusrp98** [comment]
I understand, but it seems to verbose to me.

Imaging writting
`GoogleFonts.latoTextTheme().subtitle2`
instead of 
`GoogleFonts.latoTextTheme(Theme.of(context).textTheme).subtitle2`.

@apgapg I think the smart move here would be to set `Theme.of(context).textTheme`as the default textTheme, instead of `ThemeData.light().textTheme`, as set in the current implementation.

**Comment by apgapg** [comment]
i did the same but the dark mode didnt changed color. So i created two themes one dark and light and passs the same in google fonts. In my case font was fixed for app hence i dont need to write this
```GoogleFonts.latoTextTheme(Theme.of(context).textTheme).subtitle2```
or this ```GoogleFonts.latoTextTheme().subtitle2```

**Comment by andyngdz** [comment]
Thanks @apgapg, I was getting the same issue. It works.

**Comment by treeder** [comment]
Another way to do it (also probably a dupe): https://github.com/material-foundation/google-fonts-flutter/issues/110#issuecomment-631015073

**Comment by raghav042** [comment]
for dark theme it worked fine for me
`textTheme: GoogleFonts.poppinsTextTheme(ThemeData.dark().textTheme),`
