### ISSUE TITLE
[Windows] Support offline font caching on windows

### ISSUE THREAD

**Issue by clocksmith** [material-foundation/google-fonts-flutter#70]
# Acceptance Criteria:
- Windows stores and re-uses a ttf after downloading once
- use https://github.com/google/flutter-desktop-embedding/tree/master/plugins/flutter_plugins/path_provider_fde

**Comment by MostHated** [comment]
+1 to this, please. I tried to use this just now and kept getting a path_provider error.

**Comment by YazeedAlKhalaf** [comment]
I have made a Pull Request that solves this issue here.

#114

**Comment by stuartmorgan** [comment]
Per my comment in the PR, that's not a viable solution. It doesn't make sense to change anything in this package to support Windows; it will automatically work once path_provider adds Windows support (https://github.com/flutter/plugins/pull/2818).

Individual developers can add path_provider_fde to their projects if they need a short-term workaround (which is the whole point of path_provider_fde).

**Comment by YazeedAlKhalaf** [comment]
Ah Okay, I see your point ✌. Yea anyways, For people who face problems you can use my fork until path_provider supports windows officially.

My Fork: https://github.com/YazeedAlKhalaf/google-fonts-flutter

**Comment by stuartmorgan** [comment]
Or they could [use path_provider_fde directly](https://github.com/google/flutter-desktop-embedding/tree/master/plugins/flutter_plugins), which is no harder that using your fork, and preserves control over the version of the package they are using.

**Comment by YazeedAlKhalaf** [comment]
Yea I just noticed
