### ISSUE TITLE
[MacOS] Support offline font caching on mac

### ISSUE THREAD

**Issue by clocksmith** [material-foundation/google-fonts-flutter#71]
# Acceptance Criteria:
- MacOS stores and re-uses a ttf after downloading once
- use https://pub.dev/packages/path_provider_macos#-readme-tab-

**Comment by YazeedAlKhalaf** [comment]
This is solved for macOS in the regular `path_provider` package.

`https://pub.dev/packages/path_provider_macos` is now part of  `path_provider`.

I think it is safe to close this issue 😎

**Comment by guidezpl** [comment]
Indeed!
