### ISSUE TITLE
Missing Fonts

### ISSUE THREAD

**Issue by firatagdas** [material-foundation/google-fonts-flutter#73]
0.3.2 has Gelasio font. But latest version doesn't. I didn't found any message that indicates that. Can you confirm?

**Comment by yizenlim** [comment]
Lexend Exa and Sulphur points are missing too

**Comment by bremington** [comment]
BarlowCondensed missing too

**Comment by touyou** [comment]
NotoSansJP is also missing.
This repository only includes a normal Noto family. All the other locale Noto fonts are not included such as JP, KR and so on.

**Comment by geumatee** [comment]
Sarabun is also missing.

**Comment by nodinosaur** [comment]
```The google_fonts package for Flutter allows you to easily use any of the 977 fonts (and their variants) from fonts.google.com in your Flutter app.```

As above, I have found that [Oxanium](https://fonts.google.com/specimen/Oxanium) is also missing.

How frequently is this library updated?

**Comment by MickaelHrndz** [comment]
Bebas Neue is missing as well.

**Comment by cytryn** [comment]
I just checked and all those fonts are now included in version 0.3.10.
https://pub.dev/packages/google_fonts/versions/0.3.10

**Comment by yakou32** [comment]
Spartan is missing...

**Comment by johnsonmh** [comment]
Hi all, `Spartan` and 15 others fonts are now available in version [0.7.0](https://pub.dev/packages/google_fonts#-changelog-tab-)!

**Comment by C-Aniruddh** [comment]
@johnsonmh can you add Proxima Nova and Jost in the next update?
