### ISSUE TITLE
Method to fetch all the names of the fonts available through this library.

### ISSUE THREAD

**Issue by SahajRana** [material-foundation/google-fonts-flutter#75]
Hi Google!,
It's been great using this library and has reduced the work of many hours. Thanks & cheers for that!

Is there a way to get all the names of fonts in a list, available in this library?

**Comment by real1900** [comment]
I am looking for the ability to do the same. This question hasn't been answered in a month.

**Comment by johnsonmh** [comment]
Thanks for the request! Glad you're enjoying the library.

As of version [0.4.0](https://pub.dev/packages/google_fonts#040---2020-03-20), you can get a list of all the available fonts by using `GoogleFonts.asMap`!
