### ISSUE TITLE
[BUG] Need support for Inter font 

### ISSUE THREAD

**Issue by athulantonynp** [material-foundation/google-fonts-flutter#76]
Inter font is now available in Google Fonts. Please add the support for it.
https://fonts.google.com/specimen/Inter

**Comment by MaskyS** [comment]
Bump!

**Comment by MaskyS** [comment]
@johnsonmh Anything we can do to speed this up?

**Comment by GroovinChip** [comment]
Bump

**Comment by johnsonmh** [comment]
Thanks filing this, `GoogleFonts.inter` is now available in version [0.7.0](https://pub.dev/packages/google_fonts/versions/0.7.0)!
