### ISSUE TITLE
Add web support to pub.dev

### ISSUE THREAD

**Issue by Reprevise** [material-foundation/google-fonts-flutter#77]
If Google Fonts supports web, then pub.dev isn't aware of that as it only says Android and IOS are supported.

![image](https://user-images.githubusercontent.com/25782944/76144117-1dfaa280-604b-11ea-9d65-3f0dcb0280de.png)

From this latest changelog, I can assume it *does* support web:

> [0.3.9] - 2020-02-13
Fix path_provider usage for web

**Comment by Zazo032** [comment]
If minimum Flutter version is bumped to `>= 1.10.0`, it could be added following this: https://flutter.dev/docs/development/packages-and-plugins/developing-packages#plugin-platforms

**Comment by iapicca** [comment]
https://github.com/material-foundation/google-fonts-flutter/issues/12#issuecomment-576843847

**Comment by johnsonmh** [comment]
The pub.dev page was finally updated in 1.1.1! Now Android, iOS, and Web are all officially listed.
