### ISSUE TITLE
Is there a way to get all the names of fonts in a list, available in this library?

### ISSUE THREAD

**Issue by real1900** [material-foundation/google-fonts-flutter#82]
Good work. Is there a way to get all the names of fonts in a list, available in this library?

**Comment by krista-koivisto** [comment]
Not at the moment, but a pull request (#80) for getting fonts as a map where the key is the name of the font has been submitted. You will be able to get an `Iterable` of names using `GoogleFonts.asMap().keys` once that has been pulled.

**Comment by real1900** [comment]
That is perfect.

**Comment by real1900** [comment]
It seems that your pull request was merged in, but I am still unable to access `GoogleFonts.asMap().key`

**Comment by real1900** [comment]
It seems the pull request was merged. But I am unable to resolve `[0.4.0]`in my pub spec.

**Comment by krista-koivisto** [comment]
The developers have yet to publish the update to pub.dev. I'm sure it will be done in a few days. If you want the changes right away, you could depend on the git repository:
```
google_fonts:
    git: https://github.com/material-foundation/google-fonts-flutter
```

**Comment by real1900** [comment]
Can you provide an example of how to use it . The return type : 

Function({Paint background, Color backgroundColor, Color color, TextDecoration decoration, Color decorationColor, TextDecorationStyle decorationStyle, double decorationThickness, List<FontFeature> fontFeatures, double fontSize, FontStyle fontStyle, FontWeight fontWeight, Paint foreground, double height, double letterSpacing, Locale locale, List<Shadow> shadows, TextBaseline textBaseline, TextStyle textStyle, double wordSpacing})

is kind of confusing.

**Comment by real1900** [comment]
I am doing this: 

    Widget dropdown = new DropdownButton<String>(
      value: dropDownValue ?? googleFonts.keys.first,
      items: googleFonts.keys.map((String key) {
        TextStyle textStyle = GoogleFonts.getFont(key);

        return DropdownMenuItem<String>(
          value: key,
          child: Text(
            key,
            style: textStyle,
          ),
        );
      }).toList(),
      onChanged: (value) {
        setState(() {
          dropDownValue = value;
        });
      },
    );

to display a list , but it is taking forever to render. 

Any suggestions regarding that?

**Comment by krista-koivisto** [comment]
The library contains 948 fonts at the moment. Loading them all involves downloading a font, caching it and reading it for each and every one of them.

A single font variant is typically around 150 KB, that adds up to almost 150 MB of reads/writes for a single variant. Aside from general I/O bottleneck issues, you are also likely running into device I/O limitations reading and writing such a large number of files simultaneously.

It would be a good idea to load them asynchronously and only download a limited number of fonts at a time until they have all been cached.

**Comment by real1900** [comment]
OK . That makes sense. Thank you . 

Is it possible to get the textTheme based on these values such as: 

GoogleFonts.firaSansTextTheme()

Currently I am saving the key in SharedPreferences  to set the theme as: 
ThemeData _currentTheme = .......
 var googleFont = GoogleFonts.getFont(_savedKey ?? 'Fira Sans')


Widget build(BuildContext context) {
return MaterialApp(
        debugShowCheckedModeBanner: false,
        theme: _currentTheme.copyWith(
          textTheme: GoogleFonts.firaSansTextTheme().copyWith(
            headline1: googleFont.copyWith(
                fontSize: Theme.of(context).textTheme.headline1.fontSize),
            headline2: googleFont.copyWith(
                fontSize: Theme.of(context).textTheme.headline2.fontSize),
            headline3: googleFont.copyWith(
                fontSize: Theme.of(context).textTheme.headline3.fontSize),
            headline4: googleFont.copyWith(
                fontSize: Theme.of(context).textTheme.headline3.fontSize),
            headline5: googleFont.copyWith(
                fontSize: Theme.of(context).textTheme.headline3.fontSize),
            headline6: googleFont.copyWith(
                fontSize: Theme.of(context).textTheme.headline3.fontSize),
            bodyText1: googleFont.copyWith(
                fontSize: Theme.of(context).textTheme.bodyText1.fontSize),
            bodyText2: googleFont.copyWith(
                fontSize: Theme.of(context).textTheme.bodyText2.fontSize),
            caption: googleFont.copyWith(
                fontSize: Theme.of(context).textTheme.caption.fontSize),
          ),
        ),

    );

Is that the right way of using it to set the theme?

**Comment by krista-koivisto** [comment]
You should be able to do what you're going for using `apply`:

```dart
...
debugShowCheckedModeBanner: false,
theme: Theme.of(context).textTheme.apply(fontFamily: googleFont.fontFamily)
...
```

But let's not use GitHub Issues for support, it is meant for reporting issues with the library and an e-mail gets sent to the developers each time someone posts. These type of questions are better put on StackOverflow or similar places.

**Comment by johnsonmh** [comment]
Yes, thanks to @krista-koivisto this is now possible! https://github.com/material-foundation/google-fonts-flutter/pull/80 is merged and version `0.4.0` is live on pub.dev. 

The API @krista-koivisto posted above is the best way to dynamically apply a font family to a textTheme right now, but if there was interest we could add a similar API for dynamically getting a textTheme, something like `GoogleFonts.getTextTheme(String fontName)`.

**Comment by real1900** [comment]
Thanks @krista-koivisto . I think it would be great 👍 @johnsonmh

**Comment by johnsonmh** [comment]
@real1900 Version `0.4.3` is live on pub.dev with the `GoogleFonts.getTextTheme` method!
