### ISSUE TITLE
Error: google_fonts was unable to load f

### ISSUE THREAD

**Issue by rubgithub** [material-foundation/google-fonts-flutter#84]
VsCode | Win10 | flutter 1.12.13-9
I/flutter (29612): error: google_fonts was unable to load font Pacifico-Regular because the following exception occured
I/flutter (29612): Exception: Failed to load font with url: https://fonts.gstatic.com/s/a/03452c0b90c71f4088222325620904576503c4d5a3a6c563ee22d1e896788d3e.ttf

**Comment by rubgithub** [comment]
Solution:
Emulator/device needs internet connectivity.

**Comment by levent-kantaroglu** [comment]
If you have an error on macOS for Flutter desktop, try to let access with this 
https://flutter.dev/desktop#entitlements-and-the-app-sandbox
