### ISSUE TITLE
Improperly capitalized font names

### ISSUE THREAD

**Issue by marcelgarus** [material-foundation/google-fonts-flutter#87]
The current transformation from font names into Dart identifiers sometimes chooses an ugly capitalization. For example, "IBM Plex Mono" becomes `GoogleFonts.iBMPlexMono` and "IM Fell DW Pica SC" becomes `GoogleFonts.iMFellDWPicaSC`.

Let's see what the [Effective Dart](https://dart.dev/guides/language/effective-dart) guidelines have to say about this topic! There are two somewhat relevant rules:
- [**DO name other identifiers using `lowerCamelCase`.**](https://dart.dev/guides/language/effective-dart/style#do-name-other-identifiers-using-lowercamelcase)
  Class members, top-level definitions, variables, parameters, and named parameters should capitalize the first letter of each word except the first word, and use no separators.
- [**DO capitalize acronyms and abbreviations longer than two letters like words.**](https://dart.dev/guides/language/effective-dart/style#do-capitalize-acronyms-and-abbreviations-longer-than-two-letters-like-words)
  Capitalized acronyms can be hard to read, and multiple adjacent acronyms can lead to ambiguous names. For example, given a name that starts with `HTTPSFTP`, there’s no way to tell if it’s referring to HTTPS FTP or HTTP SFTP.
  To avoid this, acronyms and abbreviations are capitalized like regular words, except for two-letter acronyms. (Two-letter _abbreviations_ like ID and Mr. are still capitalized like words.)
  **Examples** include `HttpRequest` instead of `HTTPRequest` and `Id` instead of `ID`.

So, I believe we should only capitalize the first letter of each word of the font name (except the first one). "IBM Plex Mono" would become `GoogleFonts.ibmPlexMono` and "IM Fell DW Pica SC" would become `GoogleFonts.imFellDwPicaSc`.

I'd be happy to hear your opinion and implement the necessary changes.

**Comment by johnsonmh** [comment]
Good catch!

The thing we're generating is definitely wrong... 

Following the dart style guide strictly would be tricky (maybe impossible), since abbreviations and acronyms are treated differently (`DB` is all caps but `Id` is capitalized like a word) and we have no idea whether something is an abbreviation or an acronym.

But we could _definitely_ pick a cleaner/more consistent capitalization algorithm. All we do right now is remove all spaces and make the first character of the first word lower case.

A good first step would be making the _entire first word_ lowercase then removing all spaces.

This is where we do this change: https://github.com/material-foundation/google-fonts-flutter/blob/161b5ff97fd6a1632b59e64b3300e524ac31be11/generator/generator.dart#L46 We'd be grateful for the contribution if you're interested!

**Comment by marcelgarus** [comment]
> A good first step would be making the entire first word lowercase then removing all spaces.

That sounds like a reasonable approach, although I'm not sure it handles some edge cases that well.  That said, I'm sure my approach from above also has flaws.
So, let's look at some data to find out their strengths and weaknesses! I collected a few interesting edge cases from the fonts dataset into a table.

1. Your approach: Make the entire first word lowercase, then removing all spaces.
2. My initial approach: Capitalize the first letter of each word except the first one, make the rest lowercase.
3. What intuitively feels right to me.

| font name             | 1                     | 2                     | 3                     |
| --------------------- | --------------------- | --------------------- | --------------------- |
| ABeeZee               | `abeezee`             | `abeezee`             | `aBeeZee`             |
| Alegreya SC           | `alegreyaSC`          | `alegrayaSc`          | `alegreyaSC`          |
| B612 Mono             | `b612Mono`            | `b612Mono`            | `b612Mono`            |
| Cherry Cream Soda     | `cherryCreamSoda`     | `cherryCreamSoda`     | `cherryCreamSoda`     |
| IBM Plex Mono         | `ibmPlexMono`         | `ibmPlexMono`         | `ibmPlexMono`         |
| K2D                   | `k2d`                 | `k2d`                 | `k2d`                 |
| M PLUS 1p             | `mPLUS1p`             | `mPlus1p`             | `mPlus1p`             |
| Press Start 2P        | `pressStart2P`        | `pressStart2p`        | `pressStart2P`        |
| Swanky and Moo Moo    | `swankyandMooMoo`     | `swankyAndMooMoo`     | `swankyAndMooMoo`     |
| ZCOOL QingKe HuangYou | `zcoolQingKeHuangYou` | `zcoolQingkeHuangyou` | `zcoolQingKeHuangYou` |
| IM Fell DW Pica SC    | `imFellDWPicaSC`      | `imFellDwPicaSc`      | `imFellDWPicaSC`      |

Here are some of my observations:

- All-caps and non-all-caps words should be handled differently: All of "IBM" should get lowercased to `ibm`, but only the first letter of "ABeeZee" should be lowercased to `aBeeZee`.
- Word boundaries should be visible and thereby uppercase: "Swanky and Moo Moo" should become `swankyAndMooMoo` with an uppercased `And`.

I think, where we don't yet agree on is what to do about all-caps words in the middle of the name. For example, I believe you want to retain "DW" and "SC" being all-uppercased and I get that the Dart identifier should resemble the original font name as closely as possible.
TBH I tend towards lowercasing them though, because it looks more like Dart code seen in the wild, seems more friendly for all-caps words like in "m PLUS 1p" becoming `mPlus1p` instead of `mPLUS1p` and it's future proof against "SCREAMING FONT NAMES", which would become `SCREAMINGFONTNAMES` otherwise.

Also, there's a direct tradeoff between being able to discern the words and the retaining capitalization. For example, turning "ZCOOL QingKe HuangYou" into `zcoolQingkeHuangyou` groups the words together, but looses casing information while turning it into `zcoolQingKeHuangYou` retains casing while loosing word information.

What do you think about the third column of the table, are there any names you would represent differently?
Also, what do you think about all-caps words in the middle of the name and about the tradeoff with merging camel-cased words?

**Comment by johnsonmh** [comment]
Thanks for mapping out the cases! I prefer your algorithm of all the options after seeing them mapped out. 

I think it makes good sense for us to be a little more strict on the camel-case-ification of words, since like you said, `swankyAndMooMoo` needs the capital A to distinguish And as a separate word.

I also prefer how your algorithm handles `mPlus1p`.

Finally, I agree with your third column being preferable, although the differences between your third column and what your algorithm does in column 2 is negligible to me. For example, I don't personally find there to be a clear winner between `imFellDwPicaSc ` and `imFellDWPicaSC `.

@clocksmith any preferences?

**Comment by marcelgarus** [comment]
Great! Before finalizing on a decision, I want to throw in one thought on an even better algorithm:
- Split font name into words.
- For each word:
  - Make the first letter uppercase (or lowercase if it's the first word).
  - Check if it contains lowercase characters.
    - If it does, it's assumed to be in camel case already, so don't touch the other letters.
    - If it isn't, it's all-caps, so make the rest lowercase.
- Join the words.

It would make the algorithm a bit more complex, but that's not too bad of a trade-off because the code is only run once at code-generation. It would improve some edge cases where some words are already in camel case (in the table above, only two names would be different from my initial algorithm attempt: `aBeeZee` instead of `abeezee` and `zcoolQingKeHuangYou` instead of `zcoolQingkeHuangyou`).

**Comment by johnsonmh** [comment]
Sounds good to me! I like this new algorithm.

> it would make the algorithm a bit more complex, but that's not too bad of a trade-off because the code is only run once at code-generation.

Totally agree, we're not so concerned with the generator in this sense!

Do you have any interest in coding it up and making a PR?

**Comment by marcelgarus** [comment]
Sure, I'm on it!

**Comment by johnsonmh** [comment]
Version `0.5.0` is live on [pub.dev](https://pub.dev/packages/google_fonts/versions/0.5.0), thanks for the PR @marcelgarus !
