### ISSUE TITLE
Missing font

### ISSUE THREAD

**Issue by MickaelHrndz** [material-foundation/google-fonts-flutter#9]
The Google font "Tomorrow" seems to be missing from the package.

**Comment by clocksmith** [comment]
We are using a collection that has 960 fonts, but fonts.google.com now has 977, so it is likely that "Tomorrow" is in the new set, but we have to update it. We are working on a better way to automatically update new fonts.

**Comment by johnsonmh** [comment]
Thanks for flagging this! We've just published version `0.2.0`, which has the font you're looking for.

https://pub.dev/packages/google_fonts#-readme-tab-
