### ISSUE TITLE
Use Google Fonts Delevoper API

### ISSUE THREAD

**Issue by mackattack3k** [material-foundation/google-fonts-flutter#91]
It seems like a lot of fonts are missing from [fonts.gstatic.com](http://fonts.gstatic.com/s/f/directory001.pb) which is used in the generator.

Have you considered using [Google Fonts Developer API](https://developers.google.com/fonts/docs/developer_api) instead?

**Comment by johnsonmh** [comment]
Hi, thanks for the comment! We know about both API end points, there are pros and cons to each. We're hoping to get some of the missing fonts into the new API. 

Even without the missing fonts though, the API we're hitting provides benefits like including a checksum for each font file, so we can verify each file after it is downloaded for security.

**Comment by mackattack3k** [comment]
Thanks for clarifying!
