### ISSUE TITLE
[BUG] Missing 'Fira Code' font

### ISSUE THREAD

**Issue by GroovinChip** [material-foundation/google-fonts-flutter#94]
This package is missing the [Fira Code](https://fonts.google.com/specimen/Fira+Code?category=Monospace&query=fir) font

**Comment by clocksmith** [comment]
Is it the same font as what is called Fira Mono in this API?

**Comment by johnsonmh** [comment]
Thanks for filing, `Fira Code` is now available in version [0.7.0](https://pub.dev/packages/google_fonts/versions/0.7.0)!
